export const CHANGELOG = [
  {
    version: 'v3.17',
    date: '2026-05-18',
    title: '🔧 Phase A — 데이터 모델 확장 + 점수 체계 모듈',
    items: [
      '⭐ **사양서 반영**: Account_CRM_점수체계_사양서_v1.0 (가점·감점만, 등급·처우 제외)',
      '',
      '🤝 **Activity Log 신규 필드**',
      '  ↳ cross_dept_share (Boolean): 타부서 공유/협조 필요 체크박스 (10개 issue_type과 별도)',
      '  ↳ recovery_plan_date / amount / note: GAP·지연을 메울 영업활동이 있는 경우 입력',
      '  ↳ 회복 계획 입력 시 그 일자까지 리스크 알람 일시 정지 예정 (Phase B에서 적용)',
      '',
      '🚨 **GAP 분석 cause_detail 입력 강제 (validation)**',
      '  ↳ 원인 선택 후 상세 설명 비어있으면 빨간 경고 + "필수" 라벨',
      '  ↳ 점수 시스템 3-4 (GAP 원인 입력 성실도)에 반영됨',
      '',
      '📅 **가격·계약 분할 발주 스케줄**',
      '  ↳ delivery_schedule 배열: [{date, qty, note}, ...]',
      '  ↳ 계약 시작일 contract_start 필드 추가',
      '  ↳ 분할 합계가 계약 수량과 불일치 시 경고',
      '  ↳ Phase C에서 기회 파이프라인에 자동 반영 예정',
      '',
      '₩ **수주이력 통화 표시 버그 수정**',
      '  ↳ 하드코딩 $ → 통화별 동적 기호 (₩/$/€/£/¥)',
      '  ↳ 기본 통화 USD → KRW로 변경 (ProMES 데이터 정합성)',
      '  ↳ 혼합 통화 시 KPI 카드에 별도 표기',
      '',
      '🗑 **Pipeline CRM 열기 버튼 제거** (회의는 PPT로 진행 — 사용자 결정)',
      '',
      '🏷 **팀 TASK Priority 라벨 명확화**',
      '  ↳ "⭐ Priority는 영업본부장이 부여하는 지시 우선순위 (Open 이슈의 자동 P1/P2/P3와 별개)"',
      '',
      '🧮 **신규 모듈: src/lib/scoring.js — 영업 담당자 점수 산정**',
      '  ↳ 100점 만점 (영업 성과 60 + CRM 활동 품질 40 - 감점 max 20)',
      '  ↳ 영업 성과: 당월 달성률(30) + YTD 진도(20) + 전월 대비 개선(10)',
      '  ↳ CRM 품질: 접촉 빈도(10) + 이슈 해결률(10) + 14일+ 미해결(10) + GAP 입력(5) + A등급 30일 접촉(5)',
      '  ↳ 감점: 주간 0건 / A등급 45일+ 미접촉 / GAP 미분류 / 허위 입력',
      '  ↳ computeScore() / computeAllScores() — 한 담당자 또는 전체 일괄 산정',
      '  ↳ Phase D에서 Dashboard·Report·관리자 모드에 노출 예정',
      '',
      '📌 **Phase A 완료 — 후속 Phase**',
      '  ↳ B: 주간 보고 개선 (타부서 색상, 전주 이행 점검, 리스크 분리, recovery_plan 알람)',
      '  ↳ C: 월간 보고 (3개월 수주 예측, Pipeline 데이터 fetch 버그, GAP 원인별 표시, 품목·대륙 분석)',
      '  ↳ D: 관리자 모드 담당자 선택 + 내 업무 페이지 + 점수 시각화',
      '  ↳ E: 대표이사 품목별 미래 예측',
    ],
  },
  {
    version: 'v3.16',
    date: '2026-05-15',
    title: '📊 월간 보고서 PPT 자동 다운로드 (12 슬라이드)',
    items: [
      '🆕 **월간 리포트에 "📊 PPT 다운로드" 버튼 추가** (Excel 다운로드 옆)',
      '  ↳ pptxgenjs 라이브러리 사용 (브라우저 사이드 생성, 서버 X)',
      '  ↳ 16:9 와이드 슬라이드, 영업본부 그린(#2e7d32) 테마',
      '  ↳ 동적 import로 코드 분리 — 평소엔 로드 안 됨 (번들 부담 최소화)',
      '',
      '📑 **12개 슬라이드 구성**',
      '  ↳ 1: 표지 (회사명 · 월 · 작성일)',
      '  ↳ 2: 목차 (5 Chapter)',
      '  ↳ 3: [Ch1] KPI 4카드 (수주·매출 × MTD·YTD) + 자동 요약',
      '  ↳ 4: [Ch1] 전년동기 비교표 + 영업본부장 메시지 (execSummary)',
      '  ↳ 5: [Ch2] 월별 수주·매출 추이 PPT native 차트 (편집 가능)',
      '  ↳ 6: [Ch2] 사업부별 / 담당자별 실적 표 (당월+YTD 진도)',
      '  ↳ 7: [Ch3] 팀별 활동 + GAP 요약 + 팀별 GAP 원인 TOP',
      '  ↳ 8: [Ch3] 고객별 분석 (YTD 미달 Top 8 + 초과 Top 5)',
      '  ↳ 9: [Ch3] GAP 심층 (Top 4 미달 고객 — 원인·대책·인사이트 카드)',
      '  ↳ 10: [Ch4] 차월 파이프라인 + 계약 만료 D-60',
      '  ↳ 11: [Ch4] 팀별 다음 달 계획 (해외/BPU/국내)',
      '  ↳ 12: [Ch5] Pipeline CRM 신규 딜 Top 8 + AM 활동 품질',
      '',
      '🎨 **디자인 특징**',
      '  ↳ 모든 슬라이드에 컬러 헤더 + Chapter 번호',
      '  ↳ 하단 푸터 (회사명 · 월 · 페이지 번호)',
      '  ↳ KPI 색상: 🟢 정상(≥100%) / 🟡 주의(80-100%) / 🔴 위험(<80%)',
      '  ↳ 한글 폰트: 맑은 고딕 (Windows 표준)',
      '  ↳ 차트는 PowerPoint native (사용자가 데이터·디자인 편집 가능)',
      '',
      '📌 **사용 방법**',
      '  ↳ Report → 월간 리포트 탭 → 우측 상단 "📊 PPT 다운로드" 클릭',
      '  ↳ 자동 생성 후 다운로드 (파일명: Bio_Protech_월간보고서_2026년_05월_YYYYMMDD.pptx)',
      '  ↳ 다운로드 후 PowerPoint에서 자유롭게 편집 가능',
      '',
      '⚙ **기존 Excel 다운로드 그대로 유지** — 둘 다 사용 가능',
    ],
  },
  {
    version: 'v3.15.2',
    date: '2026-05-11',
    title: '🧹 옵션 B 채택 — Baseline·imports[] 로직 모두 제거, 월 단위 운영',
    items: [
      '📌 **결정**: 매주 ProMES Import이 부담 → 월 단위 운영으로 단순화',
      '',
      '🗑 **제거된 기능**',
      '  ↳ Settings → ⏬ ProMES Baseline 재설정 도구 (UI 렌더 제거, 함수는 dead code)',
      '  ↳ PromesImportTool: imports[] 자동 누적 / buildImportsArray / existingPromesOrdersById 인덱스',
      '  ↳ Report.jsx: expandWeeklyTransactions 헬퍼 → 일자 기반 필터로 복원',
      '',
      '✅ **유지된 기능**',
      '  ↳ ProMES Import (수주·매출 두 파일 받기, 거래처코드 매칭)',
      '  ↳ Account external_code 자동 저장',
      '  ↳ YTD 진도율 표시 (Dashboard 4개 통계 + 주간/월간 KPI)',
      '  ↳ Legacy 영업현황 데이터 정리 도구',
      '',
      '📊 **데이터 영향**',
      '  ↳ Firestore의 기존 ProMES transaction에 남아있는 imports[] 필드는 무해 (사용 안 됨)',
      '  ↳ 새 ProMES Import 시 imports 필드 생성 안 함',
      '  ↳ 월간/연간 리포트, 사업계획 대비 진도율 등 모든 KPI 정상 작동',
      '',
      '🔧 **운영 방식**',
      '  ↳ 매월(또는 임의 주기) ProMES 새 다운 → Settings → ProMES Import 1회',
      '  ↳ 주간 리포트는 활동·이슈 중심, 수주/매출은 월 단위(MTD/YTD)만 표시',
      '  ↳ Baseline 클릭/imports[] 관리 부담 없음',
    ],
  },
  {
    version: 'v3.15.1',
    date: '2026-05-11',
    title: '🔧 Dashboard UX 복원 + 목표미달 로직 수정 + 주간 수주 표시 제거',
    items: [
      '↩ **Dashboard 5개 카드 원래 형태로 복원** (사용자 피드백)',
      '  ↳ 알람: 상위 15건 + "▼ 전체 N건 보기" 펼치기 토글 (전체 스크롤 X)',
      '  ↳ Open 이슈: 상위 10건 + 펼치기',
      '  ↳ 긴급 관리: 상위 10건 + 펼치기',
      '  ↳ Watch 알람: D등급 6 + 진척률낮음 6 + 펼치기',
      '  ↳ 목표미달: 상위 12건 + 펼치기',
      '',
      '🐛 **목표미달 고객 로직 핵심 버그 수정**',
      '  ↳ 기존: 연간 목표 - 실적 - FCST → 5월 시점에 연말까지 부족분 (비정상, 사용자 지적)',
      '  ↳ 변경: **YTD 목표 (1~현재월 사업계획 누적) - YTD 실적** → 현재 시점 진도 부족분',
      '  ↳ 예: 사용자 보고 "69사 GAP 204억" 사례 — 연간 기준 표시였음 → YTD 기준으로 정상화',
      '',
      '📉 **주간 리포트 — 주간 수주 표시 제거** (사용자 요청)',
      '  ↳ ProMES는 월 단위 집계 → 매주 import 못하면 주간 분리 데이터 의미 없음',
      '  ↳ KPI 카드에서 "금주 수주" 제거 (4개로 축소)',
      '  ↳ 사업부 표(수주/매출)에서 "전주 누적", "금주 신규" 컬럼 제거',
      '  ↳ 표시: 당월 누적 · 당월 목표 · 달성률 + YTD 진도 카드',
      '',
      '📋 **Baseline 작동 확인** (사용자 질문)',
      '  ↳ Settings → ⏬ ProMES Baseline 재설정 도구는 정상 작동 중',
      '  ↳ delta=0인 baseline entry는 expandWeeklyTransactions에서 자동 제외됨',
      '  ↳ 단, 매주 ProMES 새로 import해야 그 주 신규 수주가 추적됨',
      '  ↳ 매주 import 안 한다면 주간 수주 컬럼은 불필요 → 이번 버전에서 제거',
    ],
  },
  {
    version: 'v3.15',
    date: '2026-05-11',
    title: '📈 진도율 (YTD vs 사업계획 누적) + 대시보드 UI 개선',
    items: [
      '🆕 **진도율 개념 도입**: 단순 연간 달성률 → 사업계획 월별 누적 기반 YTD 진도',
      '  ↳ "1~현재월 사업계획 합계" 대비 "1~현재월 실적" 비교',
      '  ↳ 🟢 정상 (≥100%) / 🟡 주의 (80-100%) / 🔴 위험 (<80%)',
      '  ↳ Shortage 금액 명시 (▼ ₩) — 부족분 즉시 인지',
      '',
      '🏠 **Dashboard 4개 통계 카드 진도율 컬럼 추가**',
      '  ↳ 지역별 / 담당자별 / 사업구분별 / 품목별',
      '  ↳ 컬럼: 연간 목표 · YTD 목표 · YTD 실적 · 진도 · Shortage',
      '  ↳ regionStats / repStats / bizTypeStats / productStats에 ytdTarget 추가',
      '',
      '🔔 **Dashboard 알람 카드 개선**',
      '  ↳ 상위 15건 → 전체 207건 스크롤 (max-height 480px)',
      '  ↳ 헤더에 6가지 트리거 조건 명시 (담당자 인식용)',
      '  ↳ 우선순위 정렬 (danger → warning → info)',
      '',
      '📋 **Dashboard 헤더에 (N건) + 트리거 조건 명기**',
      '  ↳ Open 이슈: "Activity Log status ≠ Closed"',
      '  ↳ 긴급 관리 대상: "Insight Score < 50% AND 미접촉 30일+"',
      '  ↳ Watch 알람: "D등급 OR Insight 진척률 < 30%"',
      '  ↳ 목표미달 고객: "(N사 · 총 GAP X억)" + "연간 확정 수주 + FCST < 목표"',
      '',
      '📊 **주간 리포트 KPI 카드 5개로 확장**',
      '  ↳ 신규: "📈 YTD 진도 (M월)" 카드 — 진도율 + status + Shortage 통합',
      '  ↳ MTD 달성률(당월)과 YTD 진도(연초~현재월) 분리 표시',
      '',
      '📅 **월간 리포트 YTD KPI 카드에 진도 status + Shortage**',
      '  ↳ "수주 YTD 누적달성률" → "수주 YTD 진도"',
      '  ↳ 🟢정상 / 🟡주의 / 🔴위험 라벨 + 미달액 표시',
      '',
      '🧩 **신규 헬퍼**: computeYtdProgress(plans, actualYTD) / YtdProgressBadge 컴포넌트',
      '  ↳ Dashboard.jsx에 재사용 가능한 진도율 계산기 + 인라인 표시 컴포넌트',
    ],
  },
  {
    version: 'v3.14.4',
    date: '2026-05-11',
    title: '🐛 weeklyData가 weekOffset 무시하던 버그 수정',
    items: [
      '🐛 **문제**: 이전 주 / 다음 주 클릭해도 금주 활동 KPI가 갱신 안 됨',
      '  ↳ weeklyData useMemo가 getWeekRange()를 호출 (항상 현재 주만 반환)',
      '  ↳ dependency에 weekOffset 없어서 weekOffset 변경 시 갱신 안 됨',
      '',
      '✅ **수정**: getWeekRangeByOffset(weekOffset) 사용 + dependency에 weekOffset 추가',
      '  ↳ 이전 주/다음 주 변경 시 weekLogs, weekOrders, weekActivityCount 모두 정상 갱신',
      '',
      '📝 **참고**: Open 이슈(openIssueCount)는 의도된 설계',
      '  ↳ 모든 미해결 활동 누적이라 주차와 무관 (어느 주차에서 봐도 동일)',
      '  ↳ "이 시점 기준 미해결 N건" 의미 (KPI 카드 라벨에 명시 권장)',
    ],
  },
  {
    version: 'v3.14.3',
    date: '2026-05-11',
    title: '🔧 월간 누적/MTD 달성률 핫픽스 + 롤백 옵션',
    items: [
      '🚨 **핵심 버그**: v3.14 baseline 적용 후 monthCum(월 누적)이 0이 되는 문제',
      '  ↳ 원인: monthCum = prevCum + thisWeek로 계산 → 둘 다 expand delta → baseline 적용 시 0',
      '  ↳ 결과: MTD 달성률 0%, 사업계획 대비 실적 모두 망가짐',
      '',
      '✅ **수정**: monthCum은 monthOrders/monthSales 직접 합산 (누적 amount 그대로)',
      '  ↳ monthCum = monthOrders.reduce(order_amount)',
      '  ↳ thisWeek = expand delta (그 주 신규)',
      '  ↳ prevCum = monthCum - thisWeek (자동 일관성)',
      '  ↳ baseline 영향 없이 정확한 월 누적 표시',
      '',
      '⏎ **롤백 옵션**: PromesBackfillTool에 "imports[] 완전 제거" 버튼 추가',
      '  ↳ v3.14 도입 이전 상태로 복귀 가능',
      '  ↳ 누적 amount는 보존, imports[] 추적만 제거',
      '  ↳ 사용자 안전망용 (실제로는 monthCum 핫픽스로 baseline 유지 가능)',
      '',
      '📊 **결과**:',
      '  ↳ MTD 달성률 정상 표시 (월 누적 / 월 목표)',
      '  ↳ 사업계획 대비 실적 정상',
      '  ↳ 주차별 표시는 baseline 적용 후 매주 ProMES Import 시 자동 추적',
    ],
  },
  {
    version: 'v3.14.2',
    date: '2026-05-11',
    title: '⏬ ProMES Baseline 재설정 — 주간 수주 비정상 부풀림 해결',
    items: [
      '🔥 **문제**: v3.14 백필이 모든 ProMES 누적 amount를 한 날의 delta로 attribute → 한 주에 1~5월 전체 누적이 몰림 (예: 824.3억, MTD 달성률 2903%)',
      '',
      '💡 **해결: Baseline 개념**',
      '  ↳ 백필 = "이건 historical 누적, 이미 발생한 것"',
      '  ↳ imports[0] = { date, amount, **delta: 0**, _baseline: true }',
      '  ↳ baseline은 주간 분석에서 제외 (delta=0)',
      '  ↳ 다음 ProMES Import 시 delta = newAmount - baseline.amount → 진짜 그 주 신규',
      '',
      '🔄 **PromesBackfillTool → ⏬ ProMES Baseline 재설정 도구**',
      '  ↳ 항상 표시 (이미 잘못 백필된 데이터 정정용)',
      '  ↳ 사용자가 baseline 기준일 직접 선택 (default: 직전 주 일요일)',
      '  ↳ 클릭 시 모든 ProMES imports[] 강제 재설정',
      '  ↳ 누적 amount는 그대로 보존',
      '',
      '✅ **사용 흐름**:',
      '  ① Settings → ⏬ ProMES Baseline 재설정 1회 클릭',
      '     → 824.3억 부풀림 정상화, 모든 주차 수주 = 0 (baseline이라 제외)',
      '  ② 매주 월요일에 ProMES 새 다운 → Import',
      '     → baseline 대비 delta = 그 주 신규 수주 (정확)',
      '  ③ 주간 리포트 정상 표시',
      '',
      '⚠ **주의**: Baseline 재설정 후 "그 주의 수주가 모두 0"으로 보이는 게 정상입니다.',
      '  새로운 ProMES Import을 1회 더 실행해야 그 시점부터 delta 추적이 시작됩니다.',
    ],
  },
  {
    version: 'v3.14.1',
    date: '2026-05-11',
    title: '🟢 일반 활동 펼치기 토글 + 팀 분류 버그 수정',
    items: [
      '🟢 **주간 리포트 — 일반 활동 펼치기 토글 추가** (사용자 요청: 25건 활동 중 일부만 리스트 표시 문제)',
      '  ↳ 기존: priority ≥ 2 (🟡주요/🔴긴급)만 리스트, 일반(🟢)은 카운트만 표시',
      '  ↳ 신규: "🟢 일반 활동 N건 보기" 버튼 클릭 시 펼침',
      '  ↳ 펼친 후 일반 활동도 동일 형식(고객/유형/내용/담당/상태/날짜)으로 표시',
      '  ↳ Excel 다운로드에도 일반 활동 섹션 자동 포함',
      '',
      '🐛 **팀 분류 버그 수정 — 분당서울대 등 한국 병원이 해외로 분류되던 문제**',
      '  ↳ getTeamForAccount / getTeamForAccountLocal의 fallback이 region === "한국"만 체크',
      '  ↳ 분당서울대 account의 region이 "한국"이 아니면 (Asia/공란 등) → 해외영업으로 빠짐',
      '  ↳ 해결: isDomestic() 사용 (한글명/병원 키워드/한국 region/country 통합 판단)',
      '  ↳ 이제 한글명/병원명이면 region 정보 부정확해도 국내영업으로 정상 분류',
      '',
      '📝 **Open 이슈 P1/P2/P3 자동 분류 기준 명시** (코드 주석 + SESSION_HANDOFF 참조)',
      '  ↳ P1 긴급: priority 🔴긴급 / 품질클레임 / 14일+ 미해결(A·B등급) / 5건+ 누적',
      '  ↳ P2 주의: priority 🟡주요 / 7일+ 미해결 / 2건+ 누적',
      '  ↳ P3 관리: 그 외',
    ],
  },
  {
    version: 'v3.14',
    date: '2026-05-11',
    title: '📅 ProMES Delta 추적 — 주간 리포트 정상화',
    items: [
      '🔥 **문제**: ProMES Import은 월 단위 집계 → order_date / sale_date가 모두 월 첫째 날(YYYY-MM-01)로 저장됨. 주간 리포트가 "5/3~5/9" 범위를 보면 5월 데이터가 모두 5/1로 잡혀 0건 표시.',
      '',
      '💡 **해결: Import 시점 = 그 주의 신규 수주 (Delta 추적)**',
      '  ↳ 매 ProMES Import 시점의 누적 amount와 직전 대비 delta를 transaction에 보관',
      '  ↳ 주간 리포트는 그 주 안에 import된 entry의 delta만 합산 → "그 주 신규 수주"',
      '',
      '📊 **데이터 모델 — transaction.imports[] 배열 추가**',
      '```',
      '  imports: [',
      '    { date: "2026-05-02", amount: 0,   delta: 0 },',
      '    { date: "2026-05-09", amount: 200, delta: 200 },  // 5월 1주차 수주',
      '    { date: "2026-05-16", amount: 500, delta: 300 },  // 5월 2주차 수주',
      '  ]',
      '```',
      '  ↳ 첫 import: delta = 전체 amount',
      '  ↳ 새 날짜 import: delta = 이번 amount - 직전 amount',
      '  ↳ 같은 날 재import: 마지막 entry만 갱신 (delta는 그 이전 amount 기준)',
      '',
      '🔧 **PromesImportTool 개선**',
      '  ↳ Import 시 기존 ProMES transaction의 imports[] 자동 보존 + 새 entry append',
      '  ↳ 누적 amount는 마지막 import 값 (월간 합계용)',
      '',
      '📈 **Report.jsx 주간 섹션 ProMES delta-aware**',
      '  ↳ 신규 헬퍼: expandWeeklyTransactions(transactions, start, end, amountField, dateField)',
      '  ↳ ProMES transaction의 imports[]에서 그 주의 entry만 별개 row로 expand (amount = delta, date = import 날짜)',
      '  ↳ 영업현황/수동 입력은 기존대로 일자 기반 필터',
      '  ↳ 적용 위치: weeklyData.weekOrders, sectionAData의 thisWeekOrders/prevWeekOrders/thisWeekSales/prevWeekSales (4곳)',
      '',
      '⚡ **PromesBackfillTool — One-time 백필 도구**',
      '  ↳ 이미 import된 ProMES transaction에 imports[0] 1회 채움',
      '  ↳ delta = 누적 amount 그대로 (첫 entry로 간주)',
      '  ↳ 백필 완료 후 카드 자동으로 사라짐',
      '  ↳ ⚠ 주간 리포트를 사용하려면 1회 실행 필수',
      '',
      '✅ **사용 흐름**:',
      '  ① ProMES Import 1회 (이미 완료)',
      '  ② Settings → ⚡ ProMES Delta 백필 — 1회 클릭 (기존 데이터 호환)',
      '  ③ 매주 ProMES 다시 다운로드 → Import → 그 주의 delta 자동 추적',
      '  ④ Report → 주간 리포트 정상 표시 (신규 수주, 매출, 전주 대비)',
      '',
      '🏗 **월간 리포트 영향 없음**',
      '  ↳ order_amount는 마지막 누적값이라 월간 합계는 그대로 정확',
      '  ↳ 사업계획 대비 달성률, 전년 비교 등 모두 기존과 동일',
    ],
  },
  {
    version: 'v3.13.1',
    date: '2026-05-09',
    title: '🗑 영업현황 Import UI 제거 + Legacy 데이터 정리 도구',
    items: [
      '📌 **배경**: ProMES Import 단일 소스로 전환 — 영업현황_2026.xlsm 형식 import 기능 더 이상 불필요',
      '',
      '🚮 **Settings → 영업현황 Import 카드 제거**',
      '  ↳ ProMES Import만 노출 (UI 단순화)',
      '  ↳ Legacy 코드는 빌드에 포함되지 않도록 dead code 처리 (다음 cleanup에서 완전 제거)',
      '',
      '🆕 **Settings → 🗑 기존 영업현황 Import 데이터 정리 (One-time)**',
      '  ↳ 기존 source(excel_import_영업현황 / _S) 데이터 일괄 삭제',
      '  ↳ ProMES와 이중 집계 방지',
      '  ↳ 삭제할 데이터가 0건이면 카드 자동으로 숨김 (정리 완료 후 자동 사라짐)',
      '  ↳ ProMES source 데이터는 영향 없음',
      '',
      '✅ **사용 흐름**:',
      '  ① ProMES에서 원하는 연도 모두 다운로드 (수주.xlsx + 매출.xlsx)',
      '  ② Settings → 🆕 ProMES 영업통계 Import 실행',
      '  ③ Settings → 🗑 기존 영업현황 데이터 일괄 삭제 1회 실행',
      '  ④ 카드 자동으로 사라짐 → ProMES 단일 소스 운영',
    ],
  },
  {
    version: 'v3.13',
    date: '2026-05-09',
    title: '🆕 ProMES 영업통계 Import — 새 데이터 소스 연결',
    items: [
      '📌 **배경**: 영업현황_2026.xlsm이 더 이상 갱신되지 않음. ProMES 시스템에서 매출/수주를 별도 통계로 산출.',
      '  ↳ ProMES 영업통계 리포트 → "원본 Excel" 다운로드 (수주.xlsx + 매출.xlsx 분리)',
      '',
      '🆕 **Settings → ProMES 영업통계 Import (수주 + 매출)** 신규 카드',
      '  ↳ 수주.xlsx + 매출.xlsx 별도 선택 (한쪽만 import도 가능)',
      '  ↳ 시트명 "원본 데이터" 자동 감지',
      '  ↳ 헤더: 연도/분기/월/지역코드/지역명/거래처코드/거래처명/제품군코드/제품군명/건수/수량/금액(KRW)',
      '',
      '🔗 **Account 매칭 (3단계, 자동)**',
      '  ↳ ① external_code(거래처코드 C-00xxx) 매칭 — 가장 정확',
      '  ↳ ② company_name + alias 매칭',
      '  ↳ ③ 매칭 실패 시 신규 account 자동 생성 (external_code 자동 저장)',
      '  ↳ 기존 account에 코드가 없으면 import 시 자동 보강 (재import 정확도 향상)',
      '',
      '🧮 **dedupe 키 변경**',
      '  ↳ 기존: 수주번호 → 신규: `year-month-account_id-product_code`',
      '  ↳ 같은 키 다중 행 자동 합산 (금액/수량/건수)',
      '',
      '📅 **일자 정규화**',
      '  ↳ order_date / sale_date: 월 첫째 날 (`2026-01-01`) — 월간 리포트 호환',
      '  ↳ order_month / sale_month: `2026-01` 별도 저장',
      '  ↳ year, quarter 필드 별도 저장 (집계 빠르게)',
      '',
      '🚫 **금액 0원 자동 제외** (사용자 확인: 정상 수주/매출만 인식)',
      '  ↳ ProMES 통계가 이미 취소·샘플·수리 등 비정상 데이터 정제',
      '',
      '👤 **영업담당 컬럼 부재 영향 없음**',
      '  ↳ classifyForRepView가 plan/account 기반 attribution → transaction.sales_rep 미사용',
      '  ↳ 사업계획 매칭 거래처 → plan.sales_rep / 외 거래처 → 4 버킷',
      '',
      '📊 **리포트 영향**',
      '  ↳ ✅ 월간/연간 리포트: 기존과 동일',
      '  ↳ ✅ 담당자별 집계: 정상 작동',
      '  ↳ ⚠ 주간 리포트: 일자 월 단위 → "월목표 대비 누적실적" 표시는 정상',
      '',
      '🆔 **신규 데이터 필드**',
      '  ↳ accounts: external_code (거래처코드)',
      '  ↳ order_history / sales_history: external_code, product_code, region_code, order_month/sale_month, year, quarter, count',
      '  ↳ source: excel_import_promes_O / excel_import_promes_S',
      '',
      '🔄 **기존 영업현황 Import (Legacy 표시)**',
      '  ↳ 영업현황_2026.xlsm 형식 호환 유지 (참고용 보존)',
      '  ↳ source 분리: excel_import_영업현황 / excel_import_영업현황_S 그대로',
      '',
      '🌍 **mapRegion 보강**: ProMES 표기(M.E, L.America) 추가',
    ],
  },
  {
    version: 'v3.6.1',
    date: '2026-04-29',
    title: '💾 퍼지 매칭 Phase 2 — 실제 매칭 적용 도구',
    items: [
      '✅ **체크박스 선택**: 매칭 후보 테이블에 적용 체크박스 추가',
      '  ↳ 신뢰도 90% 이상은 자동 체크 (안전한 default)',
      '  ↳ 의심스러운 매칭(70~89%)은 사용자가 직접 검토',
      '',
      '🎛 **빠른 선택 버튼**: [전체 선택] [신뢰도 90%+ 만] [전체 해제]',
      '',
      '💾 **매칭 적용 버튼**: 선택 항목 일괄 처리',
      '  ↳ 사업계획 plan들의 account_id를 영업현황 account ID로 연결',
      '  ↳ 고객 이름은 변경 없음 (사업계획 customer_name 유지)',
      '  ↳ Firestore batch save (빠름)',
      '  ↳ Report 통계가 즉시 정확해짐 (사업계획 달성률, 전년대비 등)',
      '',
      '🛡 **안전성**:',
      '  ↳ confirm 알림으로 사용자 의도 재확인',
      '  ↳ 데이터 손실 없음 (account 통합/삭제 X, ID 연결만)',
      '  ↳ 적용 후 자동 재분석 (다음 라운드 검토 가능)',
    ],
  },
  {
    version: 'v3.6',
    date: '2026-04-27',
    title: '🔍 고객명 퍼지 매칭 분석기 (Dry-run) — 사업계획 ↔ 영업현황 통합 점검',
    items: [
      '🎯 **문제 인식**: 사업계획 고객명과 영업현황 고객명이 100% 일치하지 않아 통계 왜곡',
      '  ↳ 예: "Fannin Healthcare" ↔ "Fannin Healthcare Inc." → 별도 account로 분리',
      '  ↳ 결과: 사업계획 달성률·재구매·전년대비 등 통계 부정확',
      '',
      '🔧 **신규 라이브러리**: src/lib/fuzzyMatch.js',
      '  ↳ 정규화: 대소문자/공백/회사 접미사(Inc/Ltd/Co/주식회사 등) 제거',
      '  ↳ Levenshtein distance (편집 거리) 기반 문자열 유사도',
      '  ↳ Jaccard similarity (토큰 교집합) 기반 단어 매칭',
      '  ↳ 종합 점수 (0~1) + 신뢰도 등급 (완벽/매우높음/높음/보통/낮음)',
      '',
      '📊 **Settings 신규 섹션**: 🔍 고객명 퍼지 매칭 분석',
      '  ↳ 신뢰도 임계값 5단계 선택 (50%~85%)',
      '  ↳ Dry-run: 분석만 진행, 데이터 변경 없음',
      '  ↳ 결과 표시:',
      '    · 매칭 후보 리스트 (영업현황 → 사업계획, 신뢰도, 수주/매출 금액)',
      '    · 매칭 실패 리스트 (최근접 후보 + 점수)',
      '    · 매칭 적용 시 사업계획 실적 보강 효과 (+얼마)',
      '    · 통계 변화 미리보기',
      '',
      '📌 **다음 단계 (Phase 2)**: 결과 검증 후 매칭 적용 도구 (선택 항목 일괄 통합)',
    ],
  },
  {
    version: 'v3.5.1',
    date: '2026-04-25',
    title: '🐛 수주/매출 Import — Firestore 잔여 데이터 정리 + 25배 빠른 일괄 삭제',
    items: [
      '🐛 **버그 수정**: 재Import 후에도 기존 매출 데이터가 그대로 남던 문제',
      '  ↳ 원인: 삭제 로직이 React state 기반이라 Firestore의 어제 잔여 데이터를 인식 못 함',
      '  ↳ 수정: Firestore에서 source 기준 직접 query 후 batch 삭제 (state 무관)',
      '',
      '⚡ **삭제 속도 25배 향상**',
      '  ↳ 이전: deleteDoc 하나씩 순차 (10,000건 = 약 18분 😱)',
      '  ↳ 이후: writeBatch 500건 일괄 (10,000건 = 약 40초 ⚡)',
      '',
      '💬 **명확한 진행 토스트 메시지**',
      '  ↳ 이전: "10,000건 import 완료"',
      '  ↳ 이후: "수주 import 완료: 기존 12,000건 삭제 → 신규 4,500건"',
      '',
      '📢 **사용자 조치**: 영업현황 재Import → 한 번에 깨끗하게 정리됨',
    ],
  },
  {
    version: 'v3.5',
    date: '2026-04-25',
    title: '✎ Activity Log 전면 개편 — 편집·수정이력·완료처리·활동발생일',
    items: [
      '📅 **활동 발생일 사용자 입력** (이전: 자동 오늘 날짜 고정)',
      '  ↳ 폼에 "활동 발생일" 필드 추가, 기본값 오늘',
      '  ↳ 과거 활동도 실제 발생일로 기록 가능 → 주간/월간 리포트 정확성',
      '',
      '🔀 **폼 필드 재배치**',
      '  ↳ 상단: [활동 발생일] [이슈 유형] [중요도]',
      '  ↳ 하단: [다음 액션] [다음 액션 기한] ← 짝으로 묶음 (기한 의미 명확화)',
      '',
      '✎ **편집 기능 추가** (기존에는 삭제 후 재입력만 가능)',
      '  ↳ 각 로그 카드에 "✎ 편집" 버튼 → 인라인 편집 모드',
      '  ↳ 권한: 본인 작성 로그만 편집 가능',
      '  ↳ 👑 관리자(admin)는 모든 로그 편집 가능',
      '  ↳ 편집 불가 로그는 "(본인 로그만 편집 가능)" 표시',
      '',
      '📜 **수정 이력 자동 기록**',
      '  ↳ 모든 수정 시 edit_history 배열에 저장',
      '  ↳ 언제 / 누가 / 어느 필드 변경했는지 기록',
      '  ↳ 카드 우측 "✎ N회 수정" 배지 클릭 → 상세 이력 펼침',
      '',
      '🏁 **완료 처리 시 처리 결과 필수 기록**',
      '  ↳ "완료" 버튼 클릭 → 팝업 자동 오픈',
      '  ↳ 처리 결과 설명 (필수, textarea)',
      '  ↳ 해결 방법 태그 (8종): 🤝 합의 / ✅ 요청수용 / 💰 환불 / 🔄 교환 / ❌ 거절 / ⏸ 보류 / 📤 타부서이관 / 📌 기타',
      '  ↳ 실제 해결일 (예정일과 달라질 수 있음)',
      '  ↳ 완료된 이슈 카드에 초록색 "🏁 처리 결과" 블록 표시',
      '',
      '🔐 **삭제 권한**: 본인 또는 관리자만 가능',
    ],
  },
  {
    version: 'v3.4',
    date: '2026-04-24',
    title: '🏗️ localStorage 의존 제거 + Exec Summary Firestore 통합 + Import 개선',
    items: [
      '🚀 **근본 해결**: localStorage quota 초과로 인한 흰 화면 재발 방지',
      '  ↳ 대용량 전체 데이터 백업(STORAGE_KEY) 완전 제거',
      '  ↳ Firebase Firestore가 원본 소스 — 모든 데이터 실시간 구독',
      '  ↳ 오프라인 fallback은 개별 작은 키(auth, teamMembers 등)만 유지',
      '',
      '☁️ **Exec Summary + 다음 달 계획 Firestore 이전**',
      '  ↳ 이전: localStorage (해당 브라우저에서만, 손실 위험)',
      '  ↳ 이후: app_settings 컬렉션 (여러 PC/브라우저 공유 + 영구 보관)',
      '  ↳ 일회성 마이그레이션: 기존 localStorage 값 자동 이관',
      '  ↳ 500ms 디바운싱으로 타이핑 중 Firestore 쓰기 최적화',
      '',
      '📅 **영업현황 Import 개선 재적용 (v3.3.1 롤백 분 복구)**',
      '  ↳ "🌐 전체 연도" 옵션 추가 (기본값) — 전년도 실적까지 포함',
      '  ↳ 단일 연도 선택 시 "⚠ 전년대비 비교 불가" 경고',
      '  ↳ excelDateToStr 강화 — 다양한 문자열 날짜 정규화',
      '    · ISO · YYYY/M/D · M/D/YYYY · D.M.YYYY · Date fallback',
      '',
      '📢 **사용자 조치**: Settings → "영업현황 엑셀 선택" → "전체 연도" 선택 후 Import → 주간/월간 리포트에 전년동월·전년YTD 표시 확인',
    ],
  },
  {
    version: 'v3.3',
    date: '2026-04-24',
    title: '🏆 월간 리포트 Phase C — 5페이지 스토리텔링 + 팀별 TASK + Pipeline 하이브리드',
    items: [
      '📄 #13 5페이지 스토리텔링 구조 (Chapter Header + 인쇄 페이지 구분)',
      '  ↳ Page 1 (Executive Summary): KPI · 전년동기 · 자동 요약 · 핵심 메시지',
      '  ↳ Page 2 (Key Metrics): 월별 수주/매출 · 팀별/담당자별 실적',
      '  ↳ Page 3 (Strategic Analysis): 팀별 활동+GAP · 고객별 · 4-3 GAP 심층',
      '  ↳ Page 4 (Next Month Actions): 다음 달 계획 · 차월 파이프라인 · 팀별 TASK',
      '  ↳ Page 5 (Pipeline CRM & Deep Analysis): 신규 딜 + 심층 Gap 원인',
      '  ↳ 화면에 페이지 배너 표시 + 인쇄 시 자동 페이지 구분',
      '',
      '✅ #14 팀별 월간 TASK 기능 (신규)',
      '  ↳ Firestore `team_tasks` collection CRUD',
      '  ↳ 고정 5유형: 🎯 수주만회 / 📋 계약갱신 / 🚀 신규딜 / 🔀 Cross-Selling / 📌 기타',
      '  ↳ 해외영업/BPU/국내영업 3팀 각각 카드 형태',
      '  ↳ 우선순위 P1/P2/P3 + 상태(Open/In Progress/Done) + 담당자/마감일',
      '  ↳ 상태 배지 클릭으로 Open → In Progress → Done 순환',
      '  ↳ 편집(✎) / 삭제(×) / 추가(+ TASK) 버튼',
      '',
      '🔗 #15 Pipeline CRM 하이브리드 통합 (신규)',
      '  ↳ Pipeline CRM의 `customers` 컬렉션 read-only 구독',
      '  ↳ Proposal/Evaluation/Closing 단계 딜만 필터링, 금액 높은 순 TOP 10',
      '  ↳ 예상금액 × 확률 = 가중금액 자동 계산',
      '  ↳ "Pipeline CRM 열기 ↗" 버튼으로 원본 앱 연결',
      '',
      '📋 Phase A/B/C 통합 완료 — 경영진 월간 보고 전면 재구성',
    ],
  },
  {
    version: 'v3.2',
    date: '2026-04-23',
    title: '🎯 월간 리포트 Phase B — 경영진 스토리텔링 강화',
    items: [
      '🤖 #1 자동 Executive Summary 박스 추가',
      '  ↳ KPI/GAP/파이프라인 기반 자동 요약 4줄 + 자동 종합 판단 (🟢/🟡/🔴)',
      '  ↳ 수동 섹션(0번) 위에 배치, 수동으로 편집 가능',
      '📊 #7 GAP 심층분석 요약 박스 추가',
      '  ↳ 미달/초과 고객 수·금액, 순 Gap, FCST catch-up 잠재 한눈에',
      '  ↳ 주요 원인 TOP3 태그 표시',
      '👥 #4 팀별 월간 활동에 GAP 원인 통합',
      '  ↳ 각 팀 카드에 "🔴 미달 고객수 · Gap 금액 · 원인 TOP2" 표시',
      '  ↳ 해외/BPU/국내 사업부별 책임 명확화',
      '🎯 #8 "재구매 임박" → "차월 수주 파이프라인" 재구성',
      '  ↳ 수주 가능액 + 신뢰도 (FCST 80% / 사업계획 60% / 트렌드 40%)',
      '  ↳ 가중금액 자동 계산, P1/P2/P3 우선순위 자동 분류 (가중금액 누적 50%/80%)',
      '  ↳ 전체 예상·가중 금액 한눈에, 고객명 클릭 → 상세카드',
      '📅 #2 전년실적 반영 (기존 v3.0 완료분 확인)',
      '  ↳ KPI 4카드에 전년비 % · 전년동기 비교표(MTD+YTD) · 월별 트렌드 전년 행 모두 반영됨',
      '🗑️ 레거시 Section 1~5 전면 제거 (KPI/차트/분류별/고객별/Cross-Selling/FCST)',
      '  ↳ 이미 상단 ■1~4-3에 통합된 중복 섹션',
      '',
      '📋 다음 단계 (Phase C)',
      '  · #14 팀별 TASK 기능 (team_tasks Firestore collection — 인프라 준비 완료)',
      '  · #15 Pipeline CRM 신규 딜 하이라이트 (customers 구독 — 인프라 준비 완료)',
      '  · #13 5페이지 스토리텔링 구조 재구성',
    ],
  },
  {
    version: 'v3.1',
    date: '2026-04-23',
    title: '📊 월간/주간 리포트 Phase A 간소화 — 중복 제거 + 경영진 가독성 개선',
    items: [
      '🗑️ #3 월간 "2-2 팀별 월간 매출" 섹션 제거 — KPI 및 1-2에서 이미 확인 가능',
      '🗑️ #5 월간 "Top 10 거래처" 제거 — GAP 심층 분석과 중복',
      '🔀 #6 "고객별 당월 수주" 정렬 변경 — 달성률 낮은 순 → **높은 순** (성과 우선 표시)',
      '🗑️ #9 주간/월간 "상세 분석" 섹션 제거',
      '  ↳ 주간: 금주 수주 현황/활동 요약/당월 분류별 실적/Open 이슈 등 전체 블록 제거 (팀별 통합 블록으로 정보 충분)',
      '  ↳ 월간: "상세 분석" 타이틀 제거 (월간 리포트 전체가 상세 분석이므로 중복 표현)',
      '🗑️ #10 고객유형별(typeRows/typeMonthRows) 제거 — 사업구분별과 중복, 사용처 없음',
      '🗑️ #12 AM별 활동 품질 지표에서 "액션 실행률" 컬럼 제거 (화면 + Excel export)',
      '',
      '📋 다음 단계 (Phase B, C)',
      '  · Phase B: Executive Summary 자동생성, 전년대비, GAP 요약+상세, 재구매 재구성',
      '  · Phase C: 5페이지 스토리텔링 재구조화 + 팀별 TASK + Pipeline CRM 하이브리드',
    ],
  },
  {
    version: 'v3.0.4',
    date: '2026-04-20',
    title: '🚨 근본 원인 수정 — customerPlans 필터에 team_sales 섞임 버그',
    items: [
      '🐛 전 시스템 동일 버그: p.type !== "product" 필터 → team_sales까지 포함됨',
      '  ↳ 결과: 수주 목표 계산에 매출 목표(team_sales)가 섞여 "수주 = 매출" 동일 출력',
      '  ↳ 수정: p.type === "customer" || !p.type 로 명시적 필터',
      '📁 14개 파일 일괄 수정 — Report/Dashboard/OrderReport/Progress/Settings/GapAnalysis/AccountList',
      '💡 이 버그로 인해 이전 v3.0~3.0.3 Fallback 로직이 반대로 작동: team_sales 있어도 수주 목표로 잘못 사용',
    ],
  },
  {
    version: 'v3.0.3',
    date: '2026-04-20',
    title: '사업계획 Import 버그 수정 — 고객별 시트 없어도 Import 가능',
    items: [
      '🐛 버그 수정: 고객별 시트 없는 사업계획 파일 Import 실패 문제',
      '  ↳ 이전: `wb.SheetNames[0]`(Sheet1, 메모) 선택 → 헤더 못찾아 에러',
      '  ↳ 이후: 고객별 시트 없어도 매출 목표/품목별 있으면 Import 진행',
      '🔐 Type별 plan 교체 로직 (중요!)',
      '  ↳ 이전: 매출 목표만 있는 파일 Import 시 기존 수주목표 모두 삭제됨',
      '  ↳ 이후: 해당 type(team_sales / customer / product)만 교체, 다른 type 유지',
      '📘 Settings UI 재정리 — 두 파일 유형 명확 안내',
      '  ↳ ① 수주목표 파일 (고객별 시트)',
      '  ↳ ② 사업계획 파일 (수주매출S 시트)',
      '  ↳ 각각 순서대로 업로드 가능',
    ],
  },
  {
    version: 'v3.0.2',
    date: '2026-04-20',
    title: '매출 목표 시트 선택 + 중복 행 문제 완전 해결',
    items: [
      '✅ 매출 목표 시트 우선순위 변경 — "26년도 월별수주매출S_*" 시트 최우선 선택',
      '  ↳ 이전: "월별매출" 시트 우선 (구버전/보수적 목표, 해외 164.5억)',
      '  ↳ 이후: "월별수주매출S" 시트 우선 (최신 시뮬레이션, 해외 215.6억)',
      '✅ "국내" 행 중복 합산 버그 수정 — Excel 레이아웃의 중복 행 자동 스킵',
      '  ↳ 국내(첫 행, 합계) + 국내(대리점) + 국내(직판) → 첫 행만 사용',
      '🎯 검증 결과 — 사용자 기준 파일과 100% 일치:',
      '  · 해외 215.62억 / BPU 67.87억 / 국내 37.97억 / Total 321.45억',
    ],
  },
  {
    version: 'v3.0.1',
    date: '2026-04-20',
    title: '매출 목표 Import 단위 오류 수정',
    items: [
      '🐛 매출 목표 Import 단위 변환 오류 수정 (×1000 곱셈 제거)',
      '  ↳ 사업계획 Excel은 헤더에 "[단위: 천원]"이지만 실제 셀 값은 원 단위',
      '  ↳ 수주 목표와 동일 방식으로 값 그대로 저장',
      '📢 Import 성공 메시지에 연간 매출목표 금액 명시 (검증 용이)',
      '⚠ 기존 Import된 team_sales plan은 Settings에서 재 Import 필요 (값이 1000배 큼)',
    ],
  },
  {
    version: 'v3.0',
    date: '2026-04-20',
    title: '매출 목표 대비 실적 반드시 표시 (Fallback 로직)',
    items: [
      '💰 매출 목표 표시 보장 — team_sales plan 미Import 상태에서도 매출 달성률 표시',
      '  ↳ 1순위: 사업계획 월별매출 시트 → team_sales plan (전용 매출목표)',
      '  ↳ 2순위 Fallback: customerPlans 수주목표를 팀별 집계하여 자동 사용',
      '  ↳ 주간·월간 리포트 모두 동일 로직 적용',
      '🏷 UI 투명성 — Fallback 사용 중일 때 "수주목표 기반 대체" 라벨 명시',
      '  ↳ 사용자가 전용 매출목표 Import 필요성 인지 가능',
    ],
  },
  {
    version: 'v2.9',
    date: '2026-04-20',
    title: '담당자 분류 일관성 완성 + 매출목표 Import 강화',
    items: [
      '🚨 담당자 분류 최종 통합 — "분류별 실적 상세 > 담당자별"의 영업현황 rep(Lijian/Milena/이다은 등) 완전 제거',
      '  ↳ monthlyData.repMonthRows 및 planSummary.byRep 모두 classifyForRepView() 강제 사용',
      '  ↳ 사업계획 담당자 + teamMembers + 4개 버킷(국내기타/해외기타/국내신규/해외신규)만 노출',
      '💰 매출 목표 Import 유연성 강화 — 여러 후보 시트 자동 탐색 ("월별매출", "월별수주매출S" 등)',
      '  ↳ 데이터가 있는 시트 우선 선택, 비어있으면 명확한 경고 메시지',
      '  ↳ 담당자배정 버전(_v10_담당자배정.xlsx)은 매출목표 비어있음 → _251229 버전 사용 안내',
      '📋 재발 방지: 담당자 분류 규칙 문서·코드 주석 강화',
      '  ↳ customerClassification.js 상단 주석에 ⚠️ 절대 규칙 명기',
      '  ↳ WORKFLOW.md / MEMORY.md에도 금지 패턴 + 점검 명령어 추가',
    ],
  },
  {
    version: 'v2.8',
    date: '2026-04-20',
    title: '주간 리포트 팀별 블록 전면 재구성 — 금주활동·주요이슈·Open·차주·리스크',
    items: [
      '🏢 수주·매출 현황에서 "기타" 행 제거 — 해외/BPU/국내 3사업부만 표시 (region fallback 자동)',
      '📊 주간 리포트 간소화 — YTD 사업계획 진도·차트·고객유형별 제거, 당월(MTD) 기준으로 통일',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🎯 Activity Log 중요도(priority) 필드 추가 — 🟢일반 / 🟡주요 / 🔴긴급',
      '  ↳ 입력·수정 UI 모두 지원, 로그 카드에 배지 표시',
      '  ↳ 주요이슈 자동 집계 기준: priority ≥ 2 (🟡주요+🔴긴급)',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '👥 주간 리포트 팀별 통합 블록 신규 (해외/BPU/국내 각각)',
      '  📊 금주 활동 — 컨택/수주활동/가격협의/샘플/크로스셀링 건수',
      '  🔴 주요 이슈 — 금주 발생 + priority≥주요 자동 집계 (수동 입력 불필요)',
      '  ⏳ Open 이슈 — 고객 단위 그룹핑 + P1/P2/P3 자동 우선순위 + 토글 드릴다운',
      '     (P1: priority≥긴급 or 14일+A·B등급 or 품질클레임 or 5건+ / P2: 7일+ or 2건+ / P3: 그 외)',
      '  📅 차주 계획 — 다음주 due + 금주 미완료 이월 통합',
      '  ⚠ 리스크 — 재구매 임박 + 계약만료 D-60 + 14일+ 미해결',
      'Excel Export 동일 구조로 재구성',
    ],
  },
  {
    version: 'v2.7',
    date: '2026-04-18',
    title: '월간 리포트 완성 — 담당자 재정립 + 신규/기타 분류 + GAP 심층 분석',
    items: [
      '👥 담당자별 실적 테이블 전면 재구성 (주간 + 월간 리포트 모두)',
      '  ↳ 사업계획상 담당자 + teamMembers만 표시 (그 외 모두 제외)',
      '  ↳ 국내기타·해외기타·국내신규·해외신규 4개 버킷 자동 집계',
      '  ↳ 전년도 수주 없는 고객 = "신규"로 자동 분류',
      '🔽 신규·기타 고객 토글 드릴다운 — ▸ 클릭 시 고객 리스트 펼침 (클릭 시 상세카드 이동)',
      '📊 대시보드 담당자별 목표 vs 실적 — 동일 분류 체계 적용 (system-wide 일관성)',
      '📈 OrderReport 담당자 필터 — 중앙화된 salesReps 규칙 적용',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🎯 GAP 분석 탭 개선 (고객카드):',
      '  ↳ 초과/미달 자동 판별하여 배지 표시',
      '  ↳ "대책" 필드 신규 추가 (부족분 만회 계획) / 초과 시 "지속 발전 요소"',
      '  ↳ 상세 설명란의 플레이스홀더 상황별 자동 변경',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🔍 월간 리포트 섹션 4-3 — 고객별 GAP 심층 분석 신규 (#7·#8·#9)',
      '  ↳ 미달 고객 TOP 10 (YTD 90% 미만) + 초과 고객 TOP 5 (YTD 110% 초과)',
      '  ↳ 각 고객별 통합 뷰: GAP분석(원인/상세/대책/경쟁메모/기회)',
      '  ↳ 연관 정보 자동 집계: 전략등급, 컨텍스트, 최근 3개월 이슈, 계약만료 임박, 전년비, Cross-selling',
      '  ↳ 📈 FCST Catch-up 자동 코멘트 — 향후 FCST가 Gap 만회하면 "N월까지 회복 예상" 자동 생성',
      '  ↳ 부분 만회 시 "FCST 반영 연간 달성률 XX% 예상"',
    ],
  },
  {
    version: 'v2.6',
    date: '2026-04-18',
    title: '월간 리포트 마무리 Phase 1 — KPI 카드 + 전년동기 + YTD + 고객별 미달',
    items: [
      '📊 월간 KPI 4종 카드 (수주 MTD·YTD + 매출 MTD·YTD, 달성률 + 전년비)',
      '📈 전년동기 대비 비교 표 — 수주·매출 각각 MTD/YTD × 증감액/증감률',
      '📋 YTD 누적 달성률 신규 표시 (기존에는 YTD 실적만 있어 달성률 확인 어려움)',
      '👥 고객별 당월 실적 표 — 목표 설정된 모든 고객 포함 (실적 0 포함), 달성률 낮은 순 정렬 (미달 우선 노출)',
      '  ↳ 고객명 클릭 시 상세 카드 열림, YTD Gap / 당월 Gap 자동 표시',
      '🔢 당월 분류별 실적 정렬 변경 — 연간 목표 순 → 당월 달성률 높은 순',
      '🧰 공통 유틸리티 중앙화 — customerClassification 확장(국내·해외 신규 세분화), salesReps 신설',
    ],
  },
  {
    version: 'v2.5',
    date: '2026-04-17',
    title: '매출 데이터 정확도 개선 — S시트/사업계획 매출 목표 수정',
    items: [
      '🔧 영업현황 S시트 컬럼 매핑 수정 — 실제 컬럼명 기준(고객사/매출금액/B/L Date)으로 교체',
      '  ↳ 기존에는 O시트와 동일 구조로 가정하여 매출 데이터 import 대부분 실패 상태였음',
      '  ↳ B/L Date 있고 매출금액 > 0 인 행만 "매출 확정"으로 처리, 매출대기는 별도 필드에 보관',
      '📊 사업계획 매출 목표 Import 추가 — 월별매출 시트의 "사업부별 매출" 영역 자동 파싱',
      '  ↳ 해외/BPU/국내(국내+국내(직판) 3행 자동 합산) 사업부별 월별 매출 목표 저장',
      '  ↳ type: "team_sales" plan 신설 (연/월/팀/목표)',
      '📈 주간·월간 리포트 매출 현황 수정 — 3개 사업부(해외/BPU/국내(직판포함)) 기준으로 표시',
      '  ↳ 달성률은 사업계획 팀별 매출 목표 대비 실적 (BEP·생산 CAPA 모니터링용)',
    ],
  },
  {
    version: 'v2.4',
    date: '2026-04-17',
    title: '주간 리포트 종합 개선 + 매출 데이터 Import',
    items: [
      '📊 YTD → MTD 전환 — 주간 KPI를 월단위 중심으로 재구성',
      '📅 분기별 진행 현황 표 추가 — Q1~Q4 목표/실적/달성률, 완료/진행중/예정 상태 표시',
      '👥 담당자 활동 전원 표시 — 배정 고객수 컬럼 + 컨택율 + 활동 0 담당자도 포함',
      '🔄 미완료 이슈 자동 이월 — 금주 Closed 안된 이슈가 차주 액션에 "이월" 배지로 자동 표시',
      '🖨 PDF 페이지 분할 개선 — #app 높이 제한 해제, 섹션별 page-break, 행 단위 분할',
      '🔵🟢🟡 재구매 알람 3유형 구분 — FCST(파랑) / 사업계획(초록) / 트렌드(노랑) 독립 표시',
      '  ↳ 사업계획 신규 로직 — targets[월]에 금액 있고 80% 미달성 시 D-30/D-14 단계 알람',
      '💰 매출 데이터 Import — S 시트(B/L date 기준) 동시 업로드, sales_history 컬렉션',
      '📈 주간/월간 리포트 매출 섹션 — 수주와 나란히 "매출 현황" 테이블 병행 표시',
      '  ↳ 월별 매출 추이표(12개월) + 팀별 월간 매출 테이블',
    ],
  },
  {
    version: 'v2.3',
    date: '2026-04-17',
    title: '월간 리포트 스펙 기반 재구성 (섹션 A~E)',
    items: [
      '🗓️ 월 네비게이터 — ◀이전 월 / 다음 월▶ 탐색, 기본값은 직전 완료 월',
      '📝 섹션 A — Executive Summary (핵심 메시지 3개 + 종합 판단 + 다음달 집중, 월별 자동 저장)',
      '📊 섹션 B-1 — 월별 실적 추이표 (전년실적/목표/실적/전년대비/목표대비) 12개월 × 합계',
      '🏢 섹션 B-2 — 팀별 월간 실적 (해외/BPU/국내 × 목표/실적/달성률/전년대비)',
      '👥 섹션 C — 팀별 월간 활동 분석 (Activity/신규계약/Cross-selling/미해결/컨택 + 주요이슈 TOP5)',
      '🥇 섹션 D — 주요 거래처별 실적 상위 10사 (당월/전월/증감률)',
      '📅 섹션 E — 다음 달 사업 계획 (팀별 수동 입력 + 재구매 D-30 + 계약만료 D-60 자동 나열)',
      '📥 Excel Export 2시트 — 매출-수주 Raw(값) + 월간종합_(MM월) 스펙 레이아웃',
    ],
  },
  {
    version: 'v2.2',
    date: '2026-04-16',
    title: '종합 리포트 — 주간 수주 현황 (섹션 A)',
    items: [
      '📊 주간 수주 현황 테이블 — 팀별(해외/BPU/국내) 전주 누적 · 금주 신규 · 당월 누적 · 당월 목표 · 달성률 자동 집계',
      '🗓️ 주차 네비게이터 — ◀이전 주 / 다음 주▶ 탐색, N월 N주차 라벨 표시',
      '🎯 달성률 색상 코딩 — ≥100% 파랑 / 80~99% 검정 / <80% 빨강',
      '📋 주간 이슈사항 자동 집계 — Activity Log를 영업이슈/고객지원/품질이슈/기타로 자동 분류, 팀별 표시',
      '📅 다음 주 예정 액션 — 기한 도래 액션 + 재구매 임박 고객(D-14) 자동 표시',
      '📥 Excel Export — 스펙 기반 주간종합 시트 (섹션 A/B/C + 부록)',
    ],
  },
  {
    version: 'v2.1',
    date: '2026-04-16',
    title: '수주목표관리 개선 + 계약상태 모니터링',
    items: [
      '💱 통화 KRW 통일 — FCST/수주실적/목표 모두 원화(억/만) 표시로 통합',
      '📊 GAP 컬럼 추가 — 월별/분기/연간 (목표 - 확정 - FCST) 갭 자동 계산',
      '📋 계약 체결 현황 — 🟢계약체결 / 🟡FCST협의 / 🔴미체결 상태 대시보드 모니터링',
      '⚠️ 목표 미달 경고 — 확정+FCST가 목표에 미달하는 고객 대시보드 알람',
      '👤 담당자 필터 정리 — 수주목표관리 필터에서 불필요한 담당자 제거',
      '🐛 계약수량 저장 오류 수정 — 기존 계약 편집 시 수량이 새로고침 후 사라지는 버그 해결',
    ],
  },
  {
    version: 'v2.0',
    date: '2026-04-13',
    title: 'Customer Insight 통합 + 전략등급',
    items: [
      '🎯 전략 등급(A/B/C/D) 도입 — 고객 목록/대시보드에서 등급별 필터 및 분포 확인',
      '🔍 Customer Insight 탭 통합 — 기존 Score + 비즈니스 건강도 + 공급자 지위 + 구매결정 구조를 하나의 탭으로 통합',
      '⚡ 자동 감지 — 기본정보/가격계약 탭에 입력된 데이터를 자동으로 Insight 진척률에 반영',
      '📝 현재 컨텍스트 메모 — 고객 현황 한 줄 요약 (기본정보 탭 + 모달 헤더에 표시)',
      '⚠️ Watch 알람 — D등급 고객 + 진척률 30% 미만 고객 대시보드 알람',
      '📋 업데이트 알림 — 이 팝업! 새 버전 배포 시 변경 내역 자동 표시',
    ],
  },
  {
    version: 'v1.9',
    date: '2026-04-13',
    title: 'FCST 월별 전환 + 수주목표관리',
    items: [
      '📈 수주목표관리 리포트 뷰 신규 추가 (목표/확정수주/FCST 월별 테이블)',
      '📊 FCST 월별 입력 전환 (분기별→월별, 기존 데이터 호환)',
      '✏️ 리포트 내 FCST 인라인 편집 (셀 클릭→직접 입력)',
      '💰 가격·계약: 계약수량 + 계약금액 자동계산 추가',
    ],
  },
];

export const CURRENT_VERSION = CHANGELOG[0].version;
export const VERSION_STORAGE_KEY = 'bioprotech_account_crm_version';
