export const CHANGELOG = [
  {
    version: 'v3.30',
    date: '2026-05-26',
    title: '📊 주간 분기별 진행 현황 — 사업부(해외/BPU/국내) breakdown 추가',
    items: [
      '🆕 **사용자 요청**: 분기별 진행 현황을 사업부별로 구분',
      '',
      '🔧 **각 분기 안에 사업부 sub-row 3개 + 분기 소계** 구조로 확장',
      '  ↳ 분기 | 사업부(해외/BPU/국내) | 수주 목표·실적·달성률 | 매출 목표·실적·달성률 | 상태',
      '  ↳ 분기 셀 rowSpan=4로 묶어 시각적 분기 단위 유지',
      '  ↳ 분기 소계·연간 전체 합계 행은 배경 강조',
      '  ↳ 연간 합계도 사업부 sub-row 3개 + 전체 합계 1개로 동일 구조',
      '',
      '🧭 **집계 기준은 ■ 1(수주)/■ 1-2(매출)와 동일 헬퍼 사용**',
      '  ↳ 수주: getTeamForOrder (plan.team 우선, region/한글명 fallback)',
      '  ↳ 매출: getSalesTeamForSale (plan.team→ORDER_TEAM_TO_SALES 매핑, region fallback)',
      '  ↳ 해외기타·해외신규 → 해외 / 국내기타·국내신규 → 국내 자동 포함',
      '  ↳ 분기 소계·전체 합계는 기존 총액과 동일 (사업부 분류 변경 무영향)',
    ],
  },
  {
    version: 'v3.29',
    date: '2026-05-25',
    title: '🔮 미래 예측 정리 — 차월 파이프라인 제거 + 품목 예측 공식 보정',
    items: [
      '🧹 **차월 수주 파이프라인(■ 5-1) 제거**',
      '  ↳ 3개월 예측(■ 5-2)의 M+1과 수치가 불일치해 혼선 → 차월 금액은 ■ 5-2 M+1 단일 기준으로 통일',
      '  ↳ 미래 예측 화면이 (차월·3개월·품목) 3개 → (3개월·품목) 2개로 단순화',
      '  ↳ 자동 Executive Summary의 "차월 파이프라인 기회" 문구도 함께 제외',
      '',
      '🔧 **품목별 미래예측(■ 9-2) 공식 보정** — 전 품목이 위험으로 뜨던 문제 해결',
      '  ↳ 기존: 예측 = YTD실적 + 영업활동 (사업계획 미반영 → 활동 비면 전부 미달)',
      '  ↳ 변경: 예측 = YTD실적 + **남은 사업계획 × 50%(기본)** + 영업활동',
      '  ↳ 활동 입력한 품목은 높게, 안 한 품목은 사업계획 절반이 바닥으로 깔림',
      '',
      '🏷 **판정 라벨 100% 기준 이분법**: 현실 예측 100% 이상 = 🟢 초과(목표달성), 미만 = 🔴 미달',
    ],
  },
  {
    version: 'v3.28',
    date: '2026-05-25',
    title: '🐛 품목별 미래예측 — 크로스셀링 탭 누락 수정',
    items: [
      '🐛 **사용자 지적**: 품목별 미래예측에서 전 품목이 위험/주의 상태',
      '  ↳ 원인: 크로스셀링 집계가 account.gap.opportunities만 보고 account.cross_selling[] 탭은 누락',
      '  ↳ (monthlyPipeline은 v3.21에서 둘 다 추가됐는데 productFutureForecast만 빠져 있었음)',
      '',
      '🔧 **productFutureForecast 크로스셀링 집계에 cross_selling 탭 추가**',
      '  ↳ (a) GAP 분석 탭 기회 (gap.opportunities) + (b) 크로스셀링 탭 (cross_selling[]) 둘 다 합산',
      '  ↳ ERBE 등 영업이 크로스셀링 탭에 입력한 미래 기회가 품목 예측에 반영',
      '  ↳ 선택월 이후 + 품목 매칭 + 미완료 상태만 (확률 가중)',
      '',
      '⚠ **한계 안내**: 품목별 예측은 영업활동에 "품목"이 기입돼야 매칭됨',
      '  ↳ 품목 미지정 FCST/기회/계약은 어느 품목인지 모호해 제외됨',
      '  ↳ 정확한 예측을 위해 영업활동 입력 시 품목 기입 권장',
    ],
  },
  {
    version: 'v3.27',
    date: '2026-05-25',
    title: '📊 주간 분기별 진행 현황 — 매출 추가 (수주 + 매출 통합)',
    items: [
      '🆕 **사용자 요청**: 주간 ■ 분기별 진행 현황에 수주만 → 매출도 표시',
      '',
      '🔧 **분기별 진행 현황 표를 수주 + 매출 통합으로 확장**',
      '  ↳ 2단 헤더: 🆕 수주(목표/실적/달성률) ‖ 💰 매출(목표/실적/달성률) ‖ 상태',
      '  ↳ Q1~Q4 각 분기별로 수주·매출 나란히 비교',
      '  ↳ 연간 합계도 수주·매출 양쪽 표시',
      '',
      '📐 **매출 분기 데이터 (salesQuarterData)**',
      '  ↳ 목표: team_sales plan 우선, 없으면 customerPlans(수주목표) fallback',
      '  ↳ 실적: sales (filterValidSales — ProMES 매출) 분기별 집계',
    ],
  },
  {
    version: 'v3.26',
    date: '2026-05-25',
    title: '🔢 주간 ■ 1-4 — 사업계획 외(신규/기타) 포함, 전체 금액 일치',
    items: [
      '🐛 **사용자 지적**: ■ 1-4 고객별 합계(17.62억)가 ■ 1 수주 현황 전체(19.43억)와 불일치',
      '  ↳ 원인: ■ 1-4가 수주목표 있는 고객만 표시 → 사업계획 외(신규/기타) 1.81억 누락',
      '',
      '🔧 **사업계획 외 고객 추가 — 전체 금액 일치**',
      '  ↳ 목표 없이 당월 수주가 발생한 고객을 "🪣 사업계획 외 (신규/기타)" 그룹으로 표시',
      '  ↳ 고객명·담당자·당월실적 표시 (목표/달성률은 "-", 상태 "계획 외")',
      '  ↳ 표 구성: 사업계획 목표 고객 소계 + 사업계획 외 소계 + **전체 합계**',
      '  ↳ 전체 합계 = ■ 1 수주 현황 합계와 정확히 일치 (19.43억)',
    ],
  },
  {
    version: 'v3.25',
    date: '2026-05-25',
    title: '📋 주간보고 — 고객별 수주목표 진행 현황 신규 (■ 1-4)',
    items: [
      '🆕 **주간 보고서에 "■ 1-4. 고객별 수주목표 진행 현황" 추가**',
      '  ↳ 이번 달 수주목표가 있는 고객만 표시 (사업계획 customer plan 기준)',
      '  ↳ 컬럼: 고객명 · 담당자 · 당월목표 · 당월실적 · 달성률 · 최근활동 · Open · 상태',
      '',
      '🎯 **각 고객별 meet 여부 + 수주활동 정상 이행 점검**',
      '  ↳ 달성률 색상 (≥100% 파랑 / 80%+ 검정 / 미달 빨강)',
      '  ↳ 상태 자동 판정: ✅ 달성(100%+) / 🟡 진행중(미달+30일내 활동) / 🔴 점검필요(미달+30일↑ 또는 활동 없음)',
      '  ↳ 최근 활동일 + 경과일수 표시 (30일 초과 시 빨강 — 수주활동 정체 경고)',
      '  ↳ Open 이슈 건수 표시',
      '',
      '👤 **담당자 = 고객카드 담당자(account.sales_rep)** 기준 (절대 규칙 준수)',
      '📊 **달성률 낮은 순 정렬** — 점검 필요 고객이 상단에',
      '  ↳ 합계 행 (총 목표/실적/달성률) + 고객명 클릭 시 카드 열림',
    ],
  },
  {
    version: 'v3.24',
    date: '2026-05-25',
    title: '🔗 GAP 분석 완전 일원화 — 중복 DEEP GAP ANALYSIS 제거',
    items: [
      '🙏 **사용자 재지적**: "GAP 분석이 여전히 분산". 확인 결과 Page 5 끝에 옛 "DEEP GAP ANALYSIS" 섹션(340줄)이 남아 4-3과 중복',
      '',
      '🗑 **Page 5 끝 DEEP GAP ANALYSIS 340줄 제거** — 4개 카드 모두 다른 곳과 중복이라 옮길 필요 없이 중복본만 삭제:',
      '  ↳ Gap 원인 분석 (causeRanking) → 이미 Page 3 ■ 4-3b 원인별에 있음',
      '  ↳ 고객별 심층 분석 (topGapCustomers) → 이미 Page 3 ■ 4-3 미달 고객 카드에 있음',
      '  ↳ 기회 파이프라인 → 이미 Page 4 ■ 5-3 (v3.21 "모든 미래" 버전이 더 완전)',
      '  ↳ AM 활동 품질 (amMetrics) → 이미 Page 5 ■ 11 담당자 활동 점수에 통합됨',
      '',
      '✅ **GAP이 Page 3 ■ 4-3 한 곳으로 완전 일원화** (4-3 고객별 + 4-3b 원인별)',
      '✅ **내용 손실 0** — Excel 다운로드용 gapAnalysisData 계산은 그대로 유지',
      '',
      '📋 **지역별 Key Metrics**: 사용자 결정 — 대륙별(■ 9)로 충분, 추가 안 함',
    ],
  },
  {
    version: 'v3.23',
    date: '2026-05-25',
    title: '🧹 설정창 정리 — 고급 도구 접이식 + 죽은 코드 제거 (누더기 해소)',
    items: [
      '🙏 **사용자 지적**: 긴급 수정 때마다 도구를 덧붙여 설정창이 누더기처럼 복잡해짐',
      '',
      '🔧 **고급 도구 접이식 (`<details>` 평소 접힘)**',
      '  ↳ 자주 안 쓰는 일회성 도구 4종을 하나의 접이식 섹션으로 묶음:',
      '    · 고객 분류 일괄 적용 · Account 합병 · 정합성 진단 · 퍼지 매칭',
      '  ↳ 평소엔 "🔧 고급 도구" 한 줄만 보이고, 필요 시 클릭해서 펼침',
      '  ↳ 설정창 첫 화면이 훨씬 깔끔해짐 (일상 도구만 노출)',
      '',
      '🗑 **죽은 코드 제거**: PromesBackfillTool (185줄)',
      '  ↳ v3.14 imports[] 주차 추적 방식의 잔재 — 현재 ProMES 월 단위 운영(옵션 B)에서 미사용',
      '  ↳ 호출처 없음 확인 후 안전하게 제거 (화면·기능 영향 0)',
      '',
      '📋 **의도적 보류 (기능 손실/위험 방지 — "오류 없음" 원칙)**',
      '  ↳ ReconciliationDiagnostic: 고유 기능(사업계획↔실적 매칭 진단) 보유 + 이미 접이식 → 유지',
      '  ↳ 섹션 재배치: 거대 인라인 카드 이동 위험 → 현 상태 유지',
    ],
  },
  {
    version: 'v3.22',
    date: '2026-05-25',
    title: '🛡 긴급 — import 중복 방지 안전장치 (매출 596건 2배 사고 근본 해결)',
    items: [
      '🚨 **사고**: 주간 보고 매출이 실제 15억인데 30억(2배)으로 표시',
      '  ↳ 원인: ProMES 매출 재import 시 "기존 삭제"가 실패해도 "새 저장"이 강행 → 298+298=596건 중복',
      '  ↳ 무결성 대시보드가 자동 감지 (Import 합계 100.29억 ↔ DB 200.58억 = 100% 차이)',
      '',
      '🛠 **근본 수정 — 증상이 아니라 import 로직 자체를 고침**',
      '  ↳ `deleteByQuerySource` 강화: source 데이터가 **0건이 될 때까지 재확인 루프** (최대 6라운드)',
      '    · 1회 삭제 후 검증 없던 기존 코드 → 잔존 시 자동 재삭제',
      '    · 6라운드 후에도 잔존하면 throw (저장 중단 유도)',
      '  ↳ `importOrders` / `importSales`: **삭제 실패 시 저장 중단(return)** — 중복 원천 차단',
      '    · 이전: 삭제 실패해도 catch 후 저장 강행 (= 중복 누적)',
      '    · 이제: 삭제 실패 → "import 중단" 경고 + 저장 안 함',
      '  ↳ `countOrdersBySource` / `countSalesBySource` 헬퍼 추가 (검증용)',
      '',
      '✅ **정상화 방법**: 배포 후 ProMES 매출 재import → 596건 완전 삭제 → 298건 저장 = 정상',
      '✅ **재발 방지**: 수주·매출 모두 어떤 상황에서도 재import 시 중복 불가능',
    ],
  },
  {
    version: 'v3.21',
    date: '2026-05-20',
    title: '🔧 누락 7건 전면 재작업 — 사용자 재지적 사항 반영',
    items: [
      '🙏 v3.20에서 5건만 처리하고 배포한 점 사과. 이번엔 7건 모두 단계별 검증 후 처리.',
      '',
      '📊 **담당자 활동점수 월단위 비교 (P7)**',
      '  ↳ 대시보드에 📅 활동 점수 기준 월 드롭다운 추가 (최근 6개월)',
      '  ↳ scoring.js는 원래 yearMonth 지원 — UI 선택기만 없었음 → 추가',
      '',
      '✏️ **(P1) 자동 생성 Executive Summary 수정 가능**',
      '  ↳ "수동 수정 모드" 체크박스 → 4줄 모두 textarea 편집',
      '  ↳ 월별 Firestore 저장 (auto_summary_override_YYYY-MM)',
      '  ↳ 빈 칸이면 자동 생성값 사용, 입력하면 "수정됨" 배지 + 사용자값 우선',
      '  ↳ [↺ 자동] 버튼으로 개별 줄 초기화',
      '',
      '📋 **(P2) 팀별 활동 분석 — 상세 항상 표시**',
      '  ↳ 클릭 펼침 토글 제거 → 신규계약·크로스셀링·미해결이슈 상세 항상 표시',
      '  ↳ 각 건: 고객명(클릭→카드) · 유형 · 일자 · 담당 · 내용',
      '  ↳ 주요고객 컨택 / 하단 GAP원인 / 주요이슈 TOP 제거 (불필요)',
      '',
      '🔗 **(P3) GAP 4-3 + 4-3b 한 카드 통합**',
      '  ↳ 별도 카드 2개 → 4-3 카드 안에 4-3b를 sub-section으로 (점선 구분)',
      '  ↳ 고객별 심층 → 원인별 재분류를 한 흐름으로',
      '',
      '📝 **(P4) Page 4 흐름 재구성 — 다음달 계획 + TASK 통합**',
      '  ↳ ■ 5 팀별 박스: 다음달 계획 textarea + 그 팀 다음달 TASK 리스트 + [+ TASK 추가] 인라인',
      '  ↳ 계획→TASK 자연 흐름 → 그 다음 ■ 5-1 차월 수주 파이프라인',
      '',
      '🙈 **(P5) ■ 7 Pipeline CRM 빈 카드 hide**',
      '  ↳ 활성 딜 0건이면 카드 자체 숨김 (빈 경고 카드 제거)',
      '',
      '🤝 **(P6) 기회 파이프라인 — 모든 미래 cross_selling 반영 (ERBE 사례)**',
      '  ↳ 차월 한정 → 오늘 이후 모든 미래 cross_selling/gap.opportunities/recovery',
      '  ↳ 월별 분포 미니 요약 + 제품·확률·예정일 컬럼',
      '  ↳ ERBE 등 크로스셀링 탭 업데이트가 expected_date 무관하게 즉시 반영',
      '',
      '⚙ 모든 단계 fresh build (node_modules/.vite 비움) 검증 후 진행',
    ],
  },
  {
    version: 'v3.20',
    date: '2026-05-19',
    title: '🎯 사용자 요청 반영 — 주간 예측 입력 / 분기·반기 / 보고서 a~k 재구성 / 팀 활동 상세화',
    items: [
      '🙏 **이번엔 신중하게 단계별 검증하며 진행**. 누락·오류 없도록 단계마다 빌드 검증.',
      '',
      '📅 **주간 보고**',
      '  ↳ 수주현황·매출현황 테이블 마지막에 **수주/매출 예측 컬럼** 추가 (직접 입력)',
      '  ↳ 주차별 Firestore 자동 저장 (weekly_forecast_YYYY-MM-DD 키)',
      '  ↳ 주차 이동 시 해당 주차 입력값 자동 불러옴',
      '',
      '📊 **월간 보고**',
      '',
      '🔸 (1) **월별 실적 테이블 — 분기·반기 소계 컬럼 추가**',
      '  ↳ 1·2·3·Q1 · 4·5·6·Q2·상반기 · 7·8·9·Q3 · 10·11·12·Q4·하반기 · 합계',
      '  ↳ 수주·매출 양쪽 적용 / 분기 보라색, 반기 주황색 배경',
      '',
      '🔸 (2) **초과 고객 펼침 토글** (미달과 동일 패턴)',
      '  ↳ [▼ 전체 N사 보기 / ▲ Top 5만 보기] · 전체 초과 raw 표',
      '',
      '🔸 (3) **보고서 전체 순서 재구성 (a~k)**',
      '  ↳ Page 1 (a·b): 전체 요약 · 실질 실적 (전년동기 대비)',
      '  ↳ Page 2 (c): Key Metrics 통합 — 월별 · 팀별 · 담당자별 · 고객별 · 품목별 · 대륙별 **모두 한 곳에**',
      '  ↳ Page 3 (d·e): 팀별 활동 + GAP 통합 (4-3 고객별 + 4-3b 원인별)',
      '  ↳ Page 4 (f·g·h·i): Next Plan + 차월 파이프라인 + 3개월 예측 + 기회 파이프라인',
      '  ↳ Page 5 (j·k): 품목 미래 예측 + 담당자 활동지수',
      '',
      '🔸 (4) **■ 5 다음달 계획 textarea 제거** — ■ 6 팀별 월간 TASK로 통합',
      '',
      '🔸 (5) **차월 수주 파이프라인 (g)** — ■ 5에서 별도 카드로 분리',
      '  ↳ 6-source 통합 (FCST/사업계획/트렌드/크로스셀링/GAP기회/계약분할/회복계획)',
      '  ↳ ERBE 등 AccountModal 탭 업데이트 즉시 반영',
      '',
      '🔸 (6) **기회 파이프라인 (i) 신규** — GAP 메우는 영업 기회 단독 표시',
      '  ↳ 크로스셀링 · GAP 기회 · 회복계획만 추려낸 GAP 회복 전용 뷰',
      '',
      '🔸 (7) **팀별 활동 분석 상세화 (d)**',
      '  ↳ 신규계약 · 크로스셀링 · 미해결이슈 · 주요고객 컨택 각 행 클릭 시 펼침',
      '  ↳ 어느 회사의 어떤 건인지 (일자 · 담당자 · 내용) 표시',
      '  ↳ 컨택 회사명은 칩 형태, 활동 상세는 라인별 — 클릭 시 고객 카드 오픈',
      '',
      '🔸 (8) **품목별 미래 예측 — 대표보고용 멘트 제거**',
      '  ↳ "대표이사 요구사항" 코멘트 삭제, 시나리오 정의만 유지',
      '',
      '⚠ **별도 작업 권장 (다음 세션)**: 모든 metric 테이블 9컬럼 통일 (담당/당월목표/당월실적/달성률/Gap/YTD목표/YTD실적/YTD달성률/YTD Gap). teamRows·repMonthRows 데이터 구조 확장 필요.',
    ],
  },
  {
    version: 'v3.19',
    date: '2026-05-19',
    title: '🔧 누락 작업 정상 반영 — 차월 파이프라인 6-source + GAP 통합 순서',
    items: [
      '🙏 **솔직한 사과** — 이전 세션들에서 "완료" 보고했으나 실제로 코드에 반영 안 된 작업들 정리.',
      '',
      '🎯 **A. 차월 수주 파이프라인 6-source 통합** (ERBE 사례 근본 해소)',
      '  ↳ monthlyPipeline이 fcst/plan/trend 3개만 사용했던 결함 → 6 source로 확장',
      '  ↳ 추가: 크로스셀링 (account.cross_selling[]) · GAP 기회 (account.gap.opportunities[])',
      '  ↳ 추가: 계약 분할 (price_contracts.delivery_schedule[]) · GAP 회복계획 (activity_logs.recovery_plan_*)',
      '  ↳ ERBE 등 AccountModal 탭에서 업데이트한 데이터가 즉시 차월 파이프라인에 반영',
      '  ↳ source 컬러/라벨 7종 (🔵 FCST 80% / 🟢 사업계획 60% / 🟡 트렌드 40% /',
      '     🤝 크로스셀링 확률 / 📉 GAP기회 확률 / 📑 계약분할 90% / 🛟 회복계획 70%)',
      '',
      '🔀 **B. GAP 분석 통합 + 보고서 순서 정리**',
      '  ↳ ■ 10. GAP 원인별 분석 (Pipeline CRM 페이지) → ■ 4-3b로 이동',
      '  ↳ Strategic Analysis 페이지 내 4-3 고객별 + 4-3b 원인별 = **나란히 표시**',
      '  ↳ 위 4-3 고객별 미달 분석의 원인 관점 재분류로 자연스럽게 연결',
      '  ↳ Strategic Analysis 페이지 subtitle 갱신: "4-3 고객별 + 4-3b 원인별 나란히"',
      '  ↳ Pipeline CRM 페이지 subtitle도 정리 (gapByCause 제거)',
      '',
      '⚙ **빌드 캐시 이슈도 해결** — v3.18 빌드 시 Vite가 node_modules/.vite 캐시 사용으로',
      '   CHANGELOG 변경이 일부 누락됐던 문제. 이번엔 fresh build로 검증 완료.',
    ],
  },
  {
    version: 'v3.18',
    date: '2026-05-19',
    title: '🛡 데이터 무결성 구조 개혁 — 코드 수정 시 숫자 오류 근본 차단',
    items: [
      '🎯 **사용자 핵심 요청**: "프로그램 수정 시 자꾸 데이터 오류가 발생 — 근본 원인을 찾아 없애야 함. 숫자는 거의 다 Import 값(고정된 사업계획 + 수주/매출 Import)이라 구조만 안정되면 오류가 안 날 텐데?"',
      '',
      '🛠 **근본 해결 — 3축 구조 도입**',
      '',
      '🔸 **축 1 — 단일 정답 원칙 (Single Source of Truth)**',
      '  ↳ 신규 `src/lib/aggregation.js` — 모든 화면이 호출하는 단일 집계 모듈',
      '  ↳ `filterValidOrders()` / `filterValidSales()` — source whitelist 한 곳에만 정의',
      '  ↳ Report/Dashboard/Progress/OrderReport/MyTasks 전부 동일 함수 호출',
      '  ↳ → 흩어진 집계 로직 통합. 한 곳 수정하면 모두 일관.',
      '',
      '🔸 **축 2 — Import Audit (불변 원장)**',
      '  ↳ 신규 `import_audit_logs` Firestore 컬렉션',
      '  ↳ ProMES Excel Import 시점에 **raw 합계 자동 기록** (timestamp + 연도 + 건수 + 총액 + 월별 분포)',
      '  ↳ DB가 변해도 Import 당시 정답이 영구 보존',
      '',
      '🔸 **축 3 — 자동 검증 (Regression Detection)**',
      '  ↳ `validateDataIntegrity()` — 5가지 검사 자동 실행',
      '    • 수주 source 분포 (whitelist 위반 감지)',
      '    • 매출 source 분포',
      '    • ProMES + 영업현황 잔여 동시 존재 (이중 집계 위험)',
      '    • Import 합계 ↔ DB 합계 불일치 (0.5% 이상 차이 시 ERROR)',
      '  ↳ 코드 수정 후 Settings 진입만 해도 오류 즉시 식별',
      '',
      '🖥 **Settings → 🛡 데이터 무결성 대시보드** (보고서 상단 배너 → Settings로 이동)',
      '  ↳ 상태 뱃지 (✅ 정상 / ⚠ 주의 / 🚫 오류) — 한눈에 확인',
      '  ↳ KPI 4카드: OK/WARN/ERROR 건수 · 수주 YTD · 매출 YTD · 집계 제외 건수',
      '  ↳ 검사 항목 상세 (펼침)',
      '  ↳ Import 이력 표: 시각/건수/합계/DB 현재/차이/월별',
      '    Import 합계와 DB가 일치하면 "일치 ✓", 불일치면 차이 자동 표시',
      '',
      '💡 **이제 코드 수정 후 흐름**',
      '  ↳ 1) 수정 + 배포 → 2) Settings → 무결성 대시보드 한 번 확인 → 3) 모두 OK면 안전',
      '  ↳ ERROR 발생 시 어느 항목인지 즉시 식별 가능',
    ],
  },
  {
    version: 'v3.17.11',
    date: '2026-05-19',
    title: '🗒️ 누락 3종 완성 + 데이터 무결성 배너',
    items: [
      '🗒️ **신규 페이지: 내 업무 (MyTasks)** — 사이드바 🗒️ 메뉴',
      '  ↳ ① 내 team_tasks (월별·우선순위·상태 필터, 인라인 상태 변경)',
      '  ↳ ② 내 Open 이슈 (P1/P2/P3 정렬, 클릭 시 고객 카드)',
      '  ↳ ③ 7일 내 차주 액션 (Activity Log next_action_date)',
      '  ↳ ④ 이번달 GAP 부족 거래처 (사업계획 미달, 만회 활동 필요)',
      '  ↳ 관리자 = 전체 뷰 / 일반 담당자 = 본인만 / viewAsRep = 그 담당자',
      '',
      '📝 **월간 ■ 5 다음달 계획 → TASK 일괄 등록 버튼**',
      '  ↳ textarea의 줄별 내용을 [+ TASK로 등록] 클릭 시 team_task 일괄 생성',
      '  ↳ 다음달 보고서 ■ 4-4 자동 이행 점검에 자동 반영',
      '  ↳ 줄별 처리: 빈 줄 / 주석(`//`) 제외, 5건 미리보기 후 confirm',
      '',
      '🛡 **데이터 무결성 배너 (Report 페이지 상단)**',
      '  ↳ ProMES X건 (Y억) + 영업현황 잔여 X건 (Y억) 항상 표시',
      '  ↳ 보고서 집계 총 YTD 실적 명시',
      '  ↳ manual/기타 source 발견 시 🚫 "집계 제외 X건 (Y억)" 자동 경고',
      '  ↳ 마지막 ProMES import 일자 표시 (오른쪽)',
      '  ↳ 사용자가 보고서 수치 신뢰성을 한눈에 확인 가능',
    ],
  },
  {
    version: 'v3.17.10',
    date: '2026-05-19',
    title: '🔒 긴급 — 수주 집계 ProMES 전용 + 수동 입력 영구 비활성화',
    items: [
      '🔒 **사용자 결정**: "ProMES에서 집계된 수치만 보고서에 반영. 담당자들의 수주 추가가 실적 집계에 영향을 미쳐서는 안 됨."',
      '',
      '🛡 **수주 집계 source filter — 모든 분석 화면**',
      '  ↳ 허용 source: `excel_import_promes_O` + `excel_import_영업현황` (legacy 과도기)',
      '  ↳ `manual` 등 다른 source는 보고서/대시보드/진도관리/수주목표관리에서 **영구 제외**',
      '  ↳ 적용 파일: Report.jsx, Dashboard.jsx, Progress.jsx, OrderReport.jsx',
      '  ↳ 매출도 동일: `excel_import_promes_S` + `excel_import_영업현황_S`만 집계',
      '',
      '🚫 **OrderHistory [수주 추가] 버튼 영구 제거** (재발 방지)',
      '  ↳ AccountModal → 수주이력 탭의 수동 입력 폼/버튼 삭제',
      '  ↳ "수주 데이터는 ProMES 엑셀 import만 사용 (수동 입력 비활성화)" 안내 표시',
      '  ↳ 향후 누가 어떻게 시도해도 수주를 직접 추가할 수 없음',
      '',
      '🗑 **Manual 수주 데이터 일괄 정리 도구 신규**',
      '  ↳ Settings → 🗑 수동 입력 수주 데이터 정리 카드',
      '  ↳ source=\'manual\' 모든 수주 일괄 삭제 버튼',
      '  ↳ 데이터 없으면 카드 자동 숨김',
      '',
      '💡 **결과**',
      '  ↳ 보고서/대시보드의 수주 수치 = ProMES 정확히 일치 (5월 13.7억)',
      '  ↳ 누가 어디서 수주 입력을 시도해도 실적에 반영되지 않음',
      '  ↳ Settings에서 한 번 클릭으로 잔여 manual 데이터 정리 가능',
    ],
  },
  {
    version: 'v3.17.9',
    date: '2026-05-19',
    title: '🐛 긴급 — manual 13건 원인 확인 + OrderHistory 저장 버그 수정',
    items: [
      '🐛 **원인 확정** — OrderHistory.jsx (AccountModal → 수주이력 탭)의 handleAdd 버그',
      '  ↳ customer_name 저장 안 함 → 진단에서 거래처 "—"',
      '  ↳ product_name 저장 안 함 → 제품 "—" (product_category만 있음)',
      '  ↳ created_by 저장 안 함 → 입력자 누구인지 추적 불가',
      '  ↳ AccountModal에서 누군가가 입력한 수주 13건이 정체불명으로 보였던 이유',
      '',
      '🔧 **OrderHistory.handleAdd 수정**',
      '  ↳ customer_name = account.company_name 자동 채움',
      '  ↳ product_name = product_category 동일 값 (UI에서 분리 안 됨)',
      '  ↳ sales_rep = account.sales_rep 우선 (v3.17.3 본부장 보정 패턴 동일)',
      '  ↳ created_by + created_at 신규 저장 → 입력자/시각 추적 가능',
      '',
      '🔍 **진단 화면 정보 보강 (Settings → 정합성 진단)**',
      '  ↳ account_id → accounts.company_name lookup (저장 안 됐어도 거래처명 복원)',
      '  ↳ 신규 컬럼: 담당자, 제품/카테고리, 통화, 주문번호',
      '  ↳ customer_name 비어있으면 "(account: xxx)" 형태로 ID 노출',
      '  ↳ created_by 비어있으면 "(미저장)" 명시 — 버그 발생 시점 데이터 식별',
      '',
      '💡 **이제 판단 가능**',
      '  ↳ 거래처명·제품·담당자·금액·통화 모두 보이므로 실제 수주인지 즉시 확인',
      '  ↳ ProMES에 있는 동일 거래면 → 중복, 삭제 안전',
      '  ↳ ProMES에 없는 별도 수주면 → 보존 필요',
    ],
  },
  {
    version: 'v3.17.8',
    date: '2026-05-19',
    title: '🛡 긴급 — "manual" source 정밀 진단 + 안전장치',
    items: [
      '⛔ **사용자 직전 위험 회피** — "기타" 일괄 삭제 시 source="manual" (수동 입력) 포함 발견',
      '  ↳ "manual"은 사용자가 UI에서 직접 입력한 수주 → 실제 수주일 수 있어 삭제 시 실데이터 손실 위험',
      '',
      '🔍 **manual 13건 전체 리스트 + 입력자 추적**',
      '  ↳ 샘플 5건 → 최대 50건 전체 표시',
      '  ↳ 신규 컬럼: **입력자 (created_by)**, **입력일 (created_at)**',
      '  ↳ 금액 1천만원 초과 행은 배경색 강조 (큰 금액 우선 검토)',
      '  ↳ 금액 내림차순 정렬 (5.4억 어디서 왔는지 즉시 확인)',
      '',
      '🛡 **안전장치 — "삭제확정" 강제 입력**',
      '  ↳ source="manual" 포함 시 prompt로 정확히 "삭제확정" 입력 요구',
      '  ↳ 단순 confirm 클릭으로 실수 방지',
      '  ↳ 기타 source(manual 외)는 기존 confirm 그대로',
      '',
      '💡 **사용자 의도 식별 가이드**',
      '  ↳ 같은 날 5월 14일에 다수 입력 → batch 등록 의심',
      '  ↳ 작은 금액(원 단위)이 다수 → 테스트 입력 가능성',
      '  ↳ created_by가 본인이면 의도 명확, 다른 담당자면 확인 후 결정',
    ],
  },
  {
    version: 'v3.17.7',
    date: '2026-05-19',
    title: '🎯 긴급 — "기타" source 정체 식별 + 일괄 삭제 도구',
    items: [
      '🎯 **5월 수주 5.4억 원인 확인** — 사용자 진단 결과: 5월에 ProMES 13.7억 + "기타" 11건 5.4억 → 합산 19.1억',
      '  ↳ "기타"는 ProMES/영업현황/manual 외의 알 수 없는 source 값',
      '',
      '🔍 **"기타" 카테고리 정체 식별 카드 신규**',
      '  ↳ source 값별 분류 (예: source="excel_import_xxx" / "old_import" 등)',
      '  ↳ 각 source별 건수·금액·예시 5건 (월/거래처/제품/금액/doc id)',
      '  ↳ 어떤 import 작업이 잘못 들어온 것인지 즉시 확인',
      '',
      '🗑 **"기타" source 일괄 삭제 버튼**',
      '  ↳ confirm 다이얼로그에 삭제 대상 source 목록 + 건수·금액 명시',
      '  ↳ ProMES/영업현황/manual은 보존 — "기타"만 정확히 제거',
      '  ↳ deleteOrder helper 사용 (Firestore 직접 호출 안전)',
      '',
      '✅ **사용 절차**',
      '  ↳ 1) Settings → 🔬 정합성 진단 → 기간 ~5월 → 분석',
      '  ↳ 2) ⚠ "기타" 카테고리 정체 카드 확인 → 잘못된 source면',
      '  ↳ 3) 🗑 "기타" source 일괄 삭제 클릭 → 정상화',
    ],
  },
  {
    version: 'v3.17.6',
    date: '2026-05-19',
    title: '🔍 긴급 — 월별 source breakdown + ProMES 내부 중복 감지',
    items: [
      '🚨 **긴급 사용자 보고** — "당월 누적 수주 19.1억으로 나오는데 ProMES 임포트는 13.7억"',
      '  ↳ 정합성 진단 기간 옵션이 ~4월까지만 있어 5월 인플레이션 위치 미식별',
      '',
      '🆕 **기간 옵션 확장** (월별 임의 cutoff 가능)',
      '  ↳ ~5월 / ~7월 / ~8월 / ~10월 / ~11월 신규',
      '',
      '📅 **월별 source 분포 breakdown 표 신규**',
      '  ↳ 각 월별로 ProMES · 영업현황(잔여) · 수동 · 기타 건수/금액 동시 표시',
      '  ↳ 한 월에 ProMES + 영업현황 잔여 동시 존재 시 🚨 행 강조',
      '  ↳ 어느 월에 인플레이션이 있는지 시각적으로 즉시 확인',
      '',
      '🔁 **ProMES 내부 중복 감지 신규**',
      '  ↳ dedupe key (월 + account_id + product_code) 기준 2건 이상 항목 추적',
      '  ↳ ProMES 재임포트 시 기존 미삭제로 인한 중복 즉시 식별',
      '  ↳ 중복 키별 건수·합계·예시 (고객/제품/금액) 상위 10개 표시',
      '',
      '💡 **사용법** — Settings → 🔬 정합성 진단 → 기간 "~5월" → 분석 시작',
      '  ↳ 월별 표에서 5월 행 확인 (legacy 영업현황 칸 또는 중복 카드)',
    ],
  },
  {
    version: 'v3.17.4',
    date: '2026-05-19',
    title: '🚨 긴급 — 정합성 진단 ProMES 반영 + 이중 집계 감지',
    items: [
      '🚨 **긴급 수정** — 사용자 보고: "보고서의 실적 수치가 다 오류" + 정합성 진단이 영업현황 기준으로 남아 있어 ProMES로 받는 현재 데이터와 불일치',
      '',
      '🔬 **정합성 진단 카드 전면 개편** — Settings → ReconciliationDiagnostic',
      '  ↳ 카드 제목: "사업계획 ↔ 영업현황 정합성 진단" → "사업계획 ↔ 실적 정합성 진단"',
      '  ↳ 서브타이틀: "[ProMES + 잔여 영업현황 통합 분석]" 명시',
      '  ↳ KPI 라벨: "영업현황 YTD 총 실적" → "YTD 총 실적 (모든 source 합산)"',
      '',
      '🔍 **데이터 source별 분포 진단 신규**',
      '  ↳ 주문/매출 source별 건수·금액 분류 (promes / legacy 영업현황 / manual / other)',
      '  ↳ ProMES + 영업현황 잔여가 동시에 존재하면 🚨 **이중 집계 경고 배너** 자동 표시',
      '  ↳ "🔧 즉시 조치" 가이드 — "🗑 영업현황 데이터 일괄 삭제" 카드로 안내',
      '',
      '💡 **영향**',
      '  ↳ 보고서 실적 부풀림 원인 즉시 진단 가능',
      '  ↳ 사업계획 대비 YTD 갭이 ProMES 단독 수치인지 합산 수치인지 명확히 구분',
    ],
  },
  {
    version: 'v3.17.3',
    date: '2026-05-18',
    title: '👤 Activity Log 담당자 자동 정정 (본부장 입력 시에도 고객 담당자로 집계)',
    items: [
      '🐛 **문제**: 본부장(관리자)이 활동 입력 시 sales_rep이 본부장 이름으로 저장됨',
      '  ↳ 결과: 리포트 담당자별 집계에서 본부장(haksu) 활동이 잘못 카운트',
      '',
      '✅ **신규 입력 로직 수정** — ActivityLog.handleAdd',
      '  ↳ sales_rep = draft?.sales_rep (그 고객의 담당자) || currentUser (fallback)',
      '  ↳ 본부장이 입력해도 그 고객 담당자 이름으로 저장',
      '  ↳ created_by 필드 신규 — 실제 입력자(본부장) 별도 보존',
      '',
      '🔧 **Settings → 👤 Activity Log 담당자 일괄 정정 도구**',
      '  ↳ 기존 잘못 저장된 활동 일괄 정정 (account.sales_rep으로 통일)',
      '  ↳ created_by에 원래 입력자 자동 백업',
      '  ↳ 정정 대상 0건이면 카드 자동 숨김',
      '',
      '📊 **결과**',
      '  ↳ 점수 시스템·리포트 담당자별 집계가 그 고객 담당자 기준으로 정확',
      '  ↳ 본부장 활동이 다른 담당자에 영향 안 미침',
    ],
  },
  {
    version: 'v3.17.2',
    date: '2026-05-18',
    title: '🧬 활동 점수 통합 (사양서 v1.0 기반) + PPT 일시 제거',
    items: [
      '🧬 **월간 리포트 — AM별 활동 품질 표 → 담당자 활동 점수 통합표로 교체**',
      '  ↳ 점수 시스템 (사양서 v1.0) = 메인 평가 도구',
      '  ↳ AM 활동 품질의 정성 정보만 보완 (Insight, 액션 완료율, Gap 원인 Top 3)',
      '  ↳ 중복 항목 제거: 90일 컨택 / YTD 달성률 (점수 항목에 포함되어 있음)',
      '',
      '📐 **통합 표 컬럼**',
      '  ↳ 정량: 담당자 · 총점(100) · 영업성과(60) · CRM품질(40) · 감점',
      '  ↳ 정성 보완: 고객수 · 평균 Insight · 액션 완료율 · Gap 원인 Top 3',
      '  ↳ 등급 색상 (S/A/B/C/D) 자동 적용',
      '',
      '🗑 **리포트 PPT 다운로드 기능 일시 제거** (사용자 요청 — 추후 보완 예정)',
      '  ↳ 버튼 + handlePptDownload 함수 제거',
      '  ↳ pptxgenjs 의존성 + src/lib/pptExport.js 모듈은 보존 (재활성화 가능)',
      '',
      '✅ **일관성**: Dashboard ScoreCardSection / TeamScoreboard + 월간 리포트 통합 점수표가 동일 scoring.js 사용',
    ],
  },
  {
    version: 'v3.17.1',
    date: '2026-05-18',
    title: '🧩 주간 KPI에 담당자별 break down — 한눈에 분배 확인',
    items: [
      '🆕 **주간 리포트 KPI 카드 헤드에 담당자별 분배 표시**',
      '  ↳ "금주 활동 62건" → 칩 형태로 "Iris 18 / Rebecca 12 / Ian 9 / ..." (활동 많은 순)',
      '  ↳ "Open 이슈 43건" → "Iris 12 / Rebecca 8 / ..." (5건↑ 빨강, 3건↑ 주황)',
      '  ↳ 헤드만 봐도 각 담당자 활동/이슈 분배가 직관적으로 보임',
      '  ↳ 하단 상세 섹션은 그대로 유지 (보완 정보)',
      '',
      '📌 **활동 점수 통합 결정 보류**',
      '  ↳ 월간 AM 활동 품질 표 + 점수는 별도 유지 (정성 vs 정량 분리)',
      '  ↳ 필요 시 향후 통합 가능 — 현재는 사용자 의견 기다림',
    ],
  },
  {
    version: 'v3.17',
    date: '2026-05-18',
    title: '🚀 종합 업데이트 — 데이터 모델·주간·월간 보고·관리자 모드·품목 미래 예측',
    items: [
      '⭐ **사양서 v1.0 점수 체계 반영** (가점·감점만, 등급/처우 제외)',
      '',
      '🤝 **Phase A — 데이터 모델 + 점수 모듈**',
      '  ↳ Activity Log: cross_dept_share boolean (10개 issue_type과 별도)',
      '  ↳ Activity Log: recovery_plan_date/amount/note (GAP·지연 회복 영업활동)',
      '  ↳ GapAnalysis cause_detail 입력 강제 validation',
      '  ↳ PriceContract delivery_schedule 분할 발주 스케줄 + contract_start',
      '  ↳ 수주이력 통화 표시 버그 수정 ($ → 동적 ₩/$/€/£/¥)',
      '  ↳ Pipeline CRM 열기 버튼 제거 (회의는 PPT)',
      '  ↳ 팀 TASK Priority 라벨 명확화 (영업본부장 지시 우선순위)',
      '  ↳ src/lib/scoring.js 신규 — 100점 만점 (영업 60 + 품질 40 - 감점 max 20)',
      '',
      '📅 **Phase B — 주간 보고 개선**',
      '  ↳ 🤝 타부서 공유 이슈 별도 색상 섹션 (cross_dept_share=true)',
      '  ↳ 📋 전주 계획 이행 점검 + 담당자별 이행률 칩',
      '  ↳ 🔴 리스크 + 🟡 관리 중 2개 분리 (회복계획 유무)',
      '  ↳ 알람 일시 정지 로직 (recovery_plan_date / due_date 미래면 알람 중지)',
      '',
      '📊 **Phase C — 월간 보고 개선**',
      '  ↳ ■ 5-2. 3개월 수주 예측 (M+1/M+2/M+3) — 영업 3개월 선행 활동 가시화',
      '  ↳ Pipeline CRM fetch 진단 + stage 매칭 완화 (한국어 + case insensitive)',
      '  ↳ ■ 10. GAP 원인별 분석 (가중치 X, 중복 인정) + cause_detail 미입력 ⚠️ 마커',
      '  ↳ 다음달 계획 카드에 Open 이슈 등록 안내',
      '  ↳ ■ 8. 품목별 / ■ 9. 대륙별 (7개+한국) 분석 추가',
      '  ↳ GAP Top 10 외 전체 펼치기 토글',
      '',
      '👀 **Phase D — 관리자 모드 + 점수 시각화**',
      '  ↳ AccountContext: viewAsRep + effectiveCurrentUser/Admin',
      '  ↳ Topbar 드롭다운: 관리자가 담당자 시점 전환 (전체 화면 자동 필터링)',
      '  ↳ Dashboard 안내 배너 + ScoreCardSection (개인 100점 분해)',
      '  ↳ TeamScoreboard (관리자 전체 시점 — 담당자별 점수 정렬 표)',
      '  ↳ 등급 S/A/B/C/D 색상 표시',
      '',
      '🔮 **Phase E — 품목별 미래 예측 (대표이사 요구사항)**',
      '  ↳ ■ 9-2. 품목별 미래 예측 카드',
      '  ↳ 각 품목 4 영역: 현재 상황 / 진행 중 영업활동 / 미래 시나리오 / 권장 액션',
      '  ↳ 시나리오 3종: 🟢 낙관(100%) · 🟡 현실(가중) · 🔴 비관(FCST 50%)',
      '  ↳ 권장 액션 자동 생성 (목표 미달·FCST 부족·신규 기회 없음 등)',
    ],
  },
  {
    version: 'v3.16',
    date: '2026-05-15',
    title: '📊 월간 보고서 PPT 자동 다운로드 (12 슬라이드)',
    items: [
      '🆕 **월간 리포트에 "📊 PPT 다운로드" 버튼 추가** (Excel 다운로드 옆)',
      '  ↳ pptxgenjs 라이브러리 사용 (브라우저 사이드 생성, 서버 X)',
      '  ↳ 16:9 와이드 슬라이드, 영업본부 그린(#2e7d32) 테마',
      '  ↳ 동적 import로 코드 분리 — 평소엔 로드 안 됨 (번들 부담 최소화)',
      '',
      '📑 **12개 슬라이드 구성**',
      '  ↳ 1: 표지 (회사명 · 월 · 작성일)',
      '  ↳ 2: 목차 (5 Chapter)',
      '  ↳ 3: [Ch1] KPI 4카드 (수주·매출 × MTD·YTD) + 자동 요약',
      '  ↳ 4: [Ch1] 전년동기 비교표 + 영업본부장 메시지 (execSummary)',
      '  ↳ 5: [Ch2] 월별 수주·매출 추이 PPT native 차트 (편집 가능)',
      '  ↳ 6: [Ch2] 사업부별 / 담당자별 실적 표 (당월+YTD 진도)',
      '  ↳ 7: [Ch3] 팀별 활동 + GAP 요약 + 팀별 GAP 원인 TOP',
      '  ↳ 8: [Ch3] 고객별 분석 (YTD 미달 Top 8 + 초과 Top 5)',
      '  ↳ 9: [Ch3] GAP 심층 (Top 4 미달 고객 — 원인·대책·인사이트 카드)',
      '  ↳ 10: [Ch4] 차월 파이프라인 + 계약 만료 D-60',
      '  ↳ 11: [Ch4] 팀별 다음 달 계획 (해외/BPU/국내)',
      '  ↳ 12: [Ch5] Pipeline CRM 신규 딜 Top 8 + AM 활동 품질',
      '',
      '🎨 **디자인 특징**',
      '  ↳ 모든 슬라이드에 컬러 헤더 + Chapter 번호',
      '  ↳ 하단 푸터 (회사명 · 월 · 페이지 번호)',
      '  ↳ KPI 색상: 🟢 정상(≥100%) / 🟡 주의(80-100%) / 🔴 위험(<80%)',
      '  ↳ 한글 폰트: 맑은 고딕 (Windows 표준)',
      '  ↳ 차트는 PowerPoint native (사용자가 데이터·디자인 편집 가능)',
      '',
      '📌 **사용 방법**',
      '  ↳ Report → 월간 리포트 탭 → 우측 상단 "📊 PPT 다운로드" 클릭',
      '  ↳ 자동 생성 후 다운로드 (파일명: Bio_Protech_월간보고서_2026년_05월_YYYYMMDD.pptx)',
      '  ↳ 다운로드 후 PowerPoint에서 자유롭게 편집 가능',
      '',
      '⚙ **기존 Excel 다운로드 그대로 유지** — 둘 다 사용 가능',
    ],
  },
  {
    version: 'v3.15.2',
    date: '2026-05-11',
    title: '🧹 옵션 B 채택 — Baseline·imports[] 로직 모두 제거, 월 단위 운영',
    items: [
      '📌 **결정**: 매주 ProMES Import이 부담 → 월 단위 운영으로 단순화',
      '',
      '🗑 **제거된 기능**',
      '  ↳ Settings → ⏬ ProMES Baseline 재설정 도구 (UI 렌더 제거, 함수는 dead code)',
      '  ↳ PromesImportTool: imports[] 자동 누적 / buildImportsArray / existingPromesOrdersById 인덱스',
      '  ↳ Report.jsx: expandWeeklyTransactions 헬퍼 → 일자 기반 필터로 복원',
      '',
      '✅ **유지된 기능**',
      '  ↳ ProMES Import (수주·매출 두 파일 받기, 거래처코드 매칭)',
      '  ↳ Account external_code 자동 저장',
      '  ↳ YTD 진도율 표시 (Dashboard 4개 통계 + 주간/월간 KPI)',
      '  ↳ Legacy 영업현황 데이터 정리 도구',
      '',
      '📊 **데이터 영향**',
      '  ↳ Firestore의 기존 ProMES transaction에 남아있는 imports[] 필드는 무해 (사용 안 됨)',
      '  ↳ 새 ProMES Import 시 imports 필드 생성 안 함',
      '  ↳ 월간/연간 리포트, 사업계획 대비 진도율 등 모든 KPI 정상 작동',
      '',
      '🔧 **운영 방식**',
      '  ↳ 매월(또는 임의 주기) ProMES 새 다운 → Settings → ProMES Import 1회',
      '  ↳ 주간 리포트는 활동·이슈 중심, 수주/매출은 월 단위(MTD/YTD)만 표시',
      '  ↳ Baseline 클릭/imports[] 관리 부담 없음',
    ],
  },
  {
    version: 'v3.15.1',
    date: '2026-05-11',
    title: '🔧 Dashboard UX 복원 + 목표미달 로직 수정 + 주간 수주 표시 제거',
    items: [
      '↩ **Dashboard 5개 카드 원래 형태로 복원** (사용자 피드백)',
      '  ↳ 알람: 상위 15건 + "▼ 전체 N건 보기" 펼치기 토글 (전체 스크롤 X)',
      '  ↳ Open 이슈: 상위 10건 + 펼치기',
      '  ↳ 긴급 관리: 상위 10건 + 펼치기',
      '  ↳ Watch 알람: D등급 6 + 진척률낮음 6 + 펼치기',
      '  ↳ 목표미달: 상위 12건 + 펼치기',
      '',
      '🐛 **목표미달 고객 로직 핵심 버그 수정**',
      '  ↳ 기존: 연간 목표 - 실적 - FCST → 5월 시점에 연말까지 부족분 (비정상, 사용자 지적)',
      '  ↳ 변경: **YTD 목표 (1~현재월 사업계획 누적) - YTD 실적** → 현재 시점 진도 부족분',
      '  ↳ 예: 사용자 보고 "69사 GAP 204억" 사례 — 연간 기준 표시였음 → YTD 기준으로 정상화',
      '',
      '📉 **주간 리포트 — 주간 수주 표시 제거** (사용자 요청)',
      '  ↳ ProMES는 월 단위 집계 → 매주 import 못하면 주간 분리 데이터 의미 없음',
      '  ↳ KPI 카드에서 "금주 수주" 제거 (4개로 축소)',
      '  ↳ 사업부 표(수주/매출)에서 "전주 누적", "금주 신규" 컬럼 제거',
      '  ↳ 표시: 당월 누적 · 당월 목표 · 달성률 + YTD 진도 카드',
      '',
      '📋 **Baseline 작동 확인** (사용자 질문)',
      '  ↳ Settings → ⏬ ProMES Baseline 재설정 도구는 정상 작동 중',
      '  ↳ delta=0인 baseline entry는 expandWeeklyTransactions에서 자동 제외됨',
      '  ↳ 단, 매주 ProMES 새로 import해야 그 주 신규 수주가 추적됨',
      '  ↳ 매주 import 안 한다면 주간 수주 컬럼은 불필요 → 이번 버전에서 제거',
    ],
  },
  {
    version: 'v3.15',
    date: '2026-05-11',
    title: '📈 진도율 (YTD vs 사업계획 누적) + 대시보드 UI 개선',
    items: [
      '🆕 **진도율 개념 도입**: 단순 연간 달성률 → 사업계획 월별 누적 기반 YTD 진도',
      '  ↳ "1~현재월 사업계획 합계" 대비 "1~현재월 실적" 비교',
      '  ↳ 🟢 정상 (≥100%) / 🟡 주의 (80-100%) / 🔴 위험 (<80%)',
      '  ↳ Shortage 금액 명시 (▼ ₩) — 부족분 즉시 인지',
      '',
      '🏠 **Dashboard 4개 통계 카드 진도율 컬럼 추가**',
      '  ↳ 지역별 / 담당자별 / 사업구분별 / 품목별',
      '  ↳ 컬럼: 연간 목표 · YTD 목표 · YTD 실적 · 진도 · Shortage',
      '  ↳ regionStats / repStats / bizTypeStats / productStats에 ytdTarget 추가',
      '',
      '🔔 **Dashboard 알람 카드 개선**',
      '  ↳ 상위 15건 → 전체 207건 스크롤 (max-height 480px)',
      '  ↳ 헤더에 6가지 트리거 조건 명시 (담당자 인식용)',
      '  ↳ 우선순위 정렬 (danger → warning → info)',
      '',
      '📋 **Dashboard 헤더에 (N건) + 트리거 조건 명기**',
      '  ↳ Open 이슈: "Activity Log status ≠ Closed"',
      '  ↳ 긴급 관리 대상: "Insight Score < 50% AND 미접촉 30일+"',
      '  ↳ Watch 알람: "D등급 OR Insight 진척률 < 30%"',
      '  ↳ 목표미달 고객: "(N사 · 총 GAP X억)" + "연간 확정 수주 + FCST < 목표"',
      '',
      '📊 **주간 리포트 KPI 카드 5개로 확장**',
      '  ↳ 신규: "📈 YTD 진도 (M월)" 카드 — 진도율 + status + Shortage 통합',
      '  ↳ MTD 달성률(당월)과 YTD 진도(연초~현재월) 분리 표시',
      '',
      '📅 **월간 리포트 YTD KPI 카드에 진도 status + Shortage**',
      '  ↳ "수주 YTD 누적달성률" → "수주 YTD 진도"',
      '  ↳ 🟢정상 / 🟡주의 / 🔴위험 라벨 + 미달액 표시',
      '',
      '🧩 **신규 헬퍼**: computeYtdProgress(plans, actualYTD) / YtdProgressBadge 컴포넌트',
      '  ↳ Dashboard.jsx에 재사용 가능한 진도율 계산기 + 인라인 표시 컴포넌트',
    ],
  },
  {
    version: 'v3.14.4',
    date: '2026-05-11',
    title: '🐛 weeklyData가 weekOffset 무시하던 버그 수정',
    items: [
      '🐛 **문제**: 이전 주 / 다음 주 클릭해도 금주 활동 KPI가 갱신 안 됨',
      '  ↳ weeklyData useMemo가 getWeekRange()를 호출 (항상 현재 주만 반환)',
      '  ↳ dependency에 weekOffset 없어서 weekOffset 변경 시 갱신 안 됨',
      '',
      '✅ **수정**: getWeekRangeByOffset(weekOffset) 사용 + dependency에 weekOffset 추가',
      '  ↳ 이전 주/다음 주 변경 시 weekLogs, weekOrders, weekActivityCount 모두 정상 갱신',
      '',
      '📝 **참고**: Open 이슈(openIssueCount)는 의도된 설계',
      '  ↳ 모든 미해결 활동 누적이라 주차와 무관 (어느 주차에서 봐도 동일)',
      '  ↳ "이 시점 기준 미해결 N건" 의미 (KPI 카드 라벨에 명시 권장)',
    ],
  },
  {
    version: 'v3.14.3',
    date: '2026-05-11',
    title: '🔧 월간 누적/MTD 달성률 핫픽스 + 롤백 옵션',
    items: [
      '🚨 **핵심 버그**: v3.14 baseline 적용 후 monthCum(월 누적)이 0이 되는 문제',
      '  ↳ 원인: monthCum = prevCum + thisWeek로 계산 → 둘 다 expand delta → baseline 적용 시 0',
      '  ↳ 결과: MTD 달성률 0%, 사업계획 대비 실적 모두 망가짐',
      '',
      '✅ **수정**: monthCum은 monthOrders/monthSales 직접 합산 (누적 amount 그대로)',
      '  ↳ monthCum = monthOrders.reduce(order_amount)',
      '  ↳ thisWeek = expand delta (그 주 신규)',
      '  ↳ prevCum = monthCum - thisWeek (자동 일관성)',
      '  ↳ baseline 영향 없이 정확한 월 누적 표시',
      '',
      '⏎ **롤백 옵션**: PromesBackfillTool에 "imports[] 완전 제거" 버튼 추가',
      '  ↳ v3.14 도입 이전 상태로 복귀 가능',
      '  ↳ 누적 amount는 보존, imports[] 추적만 제거',
      '  ↳ 사용자 안전망용 (실제로는 monthCum 핫픽스로 baseline 유지 가능)',
      '',
      '📊 **결과**:',
      '  ↳ MTD 달성률 정상 표시 (월 누적 / 월 목표)',
      '  ↳ 사업계획 대비 실적 정상',
      '  ↳ 주차별 표시는 baseline 적용 후 매주 ProMES Import 시 자동 추적',
    ],
  },
  {
    version: 'v3.14.2',
    date: '2026-05-11',
    title: '⏬ ProMES Baseline 재설정 — 주간 수주 비정상 부풀림 해결',
    items: [
      '🔥 **문제**: v3.14 백필이 모든 ProMES 누적 amount를 한 날의 delta로 attribute → 한 주에 1~5월 전체 누적이 몰림 (예: 824.3억, MTD 달성률 2903%)',
      '',
      '💡 **해결: Baseline 개념**',
      '  ↳ 백필 = "이건 historical 누적, 이미 발생한 것"',
      '  ↳ imports[0] = { date, amount, **delta: 0**, _baseline: true }',
      '  ↳ baseline은 주간 분석에서 제외 (delta=0)',
      '  ↳ 다음 ProMES Import 시 delta = newAmount - baseline.amount → 진짜 그 주 신규',
      '',
      '🔄 **PromesBackfillTool → ⏬ ProMES Baseline 재설정 도구**',
      '  ↳ 항상 표시 (이미 잘못 백필된 데이터 정정용)',
      '  ↳ 사용자가 baseline 기준일 직접 선택 (default: 직전 주 일요일)',
      '  ↳ 클릭 시 모든 ProMES imports[] 강제 재설정',
      '  ↳ 누적 amount는 그대로 보존',
      '',
      '✅ **사용 흐름**:',
      '  ① Settings → ⏬ ProMES Baseline 재설정 1회 클릭',
      '     → 824.3억 부풀림 정상화, 모든 주차 수주 = 0 (baseline이라 제외)',
      '  ② 매주 월요일에 ProMES 새 다운 → Import',
      '     → baseline 대비 delta = 그 주 신규 수주 (정확)',
      '  ③ 주간 리포트 정상 표시',
      '',
      '⚠ **주의**: Baseline 재설정 후 "그 주의 수주가 모두 0"으로 보이는 게 정상입니다.',
      '  새로운 ProMES Import을 1회 더 실행해야 그 시점부터 delta 추적이 시작됩니다.',
    ],
  },
  {
    version: 'v3.14.1',
    date: '2026-05-11',
    title: '🟢 일반 활동 펼치기 토글 + 팀 분류 버그 수정',
    items: [
      '🟢 **주간 리포트 — 일반 활동 펼치기 토글 추가** (사용자 요청: 25건 활동 중 일부만 리스트 표시 문제)',
      '  ↳ 기존: priority ≥ 2 (🟡주요/🔴긴급)만 리스트, 일반(🟢)은 카운트만 표시',
      '  ↳ 신규: "🟢 일반 활동 N건 보기" 버튼 클릭 시 펼침',
      '  ↳ 펼친 후 일반 활동도 동일 형식(고객/유형/내용/담당/상태/날짜)으로 표시',
      '  ↳ Excel 다운로드에도 일반 활동 섹션 자동 포함',
      '',
      '🐛 **팀 분류 버그 수정 — 분당서울대 등 한국 병원이 해외로 분류되던 문제**',
      '  ↳ getTeamForAccount / getTeamForAccountLocal의 fallback이 region === "한국"만 체크',
      '  ↳ 분당서울대 account의 region이 "한국"이 아니면 (Asia/공란 등) → 해외영업으로 빠짐',
      '  ↳ 해결: isDomestic() 사용 (한글명/병원 키워드/한국 region/country 통합 판단)',
      '  ↳ 이제 한글명/병원명이면 region 정보 부정확해도 국내영업으로 정상 분류',
      '',
      '📝 **Open 이슈 P1/P2/P3 자동 분류 기준 명시** (코드 주석 + SESSION_HANDOFF 참조)',
      '  ↳ P1 긴급: priority 🔴긴급 / 품질클레임 / 14일+ 미해결(A·B등급) / 5건+ 누적',
      '  ↳ P2 주의: priority 🟡주요 / 7일+ 미해결 / 2건+ 누적',
      '  ↳ P3 관리: 그 외',
    ],
  },
  {
    version: 'v3.14',
    date: '2026-05-11',
    title: '📅 ProMES Delta 추적 — 주간 리포트 정상화',
    items: [
      '🔥 **문제**: ProMES Import은 월 단위 집계 → order_date / sale_date가 모두 월 첫째 날(YYYY-MM-01)로 저장됨. 주간 리포트가 "5/3~5/9" 범위를 보면 5월 데이터가 모두 5/1로 잡혀 0건 표시.',
      '',
      '💡 **해결: Import 시점 = 그 주의 신규 수주 (Delta 추적)**',
      '  ↳ 매 ProMES Import 시점의 누적 amount와 직전 대비 delta를 transaction에 보관',
      '  ↳ 주간 리포트는 그 주 안에 import된 entry의 delta만 합산 → "그 주 신규 수주"',
      '',
      '📊 **데이터 모델 — transaction.imports[] 배열 추가**',
      '```',
      '  imports: [',
      '    { date: "2026-05-02", amount: 0,   delta: 0 },',
      '    { date: "2026-05-09", amount: 200, delta: 200 },  // 5월 1주차 수주',
      '    { date: "2026-05-16", amount: 500, delta: 300 },  // 5월 2주차 수주',
      '  ]',
      '```',
      '  ↳ 첫 import: delta = 전체 amount',
      '  ↳ 새 날짜 import: delta = 이번 amount - 직전 amount',
      '  ↳ 같은 날 재import: 마지막 entry만 갱신 (delta는 그 이전 amount 기준)',
      '',
      '🔧 **PromesImportTool 개선**',
      '  ↳ Import 시 기존 ProMES transaction의 imports[] 자동 보존 + 새 entry append',
      '  ↳ 누적 amount는 마지막 import 값 (월간 합계용)',
      '',
      '📈 **Report.jsx 주간 섹션 ProMES delta-aware**',
      '  ↳ 신규 헬퍼: expandWeeklyTransactions(transactions, start, end, amountField, dateField)',
      '  ↳ ProMES transaction의 imports[]에서 그 주의 entry만 별개 row로 expand (amount = delta, date = import 날짜)',
      '  ↳ 영업현황/수동 입력은 기존대로 일자 기반 필터',
      '  ↳ 적용 위치: weeklyData.weekOrders, sectionAData의 thisWeekOrders/prevWeekOrders/thisWeekSales/prevWeekSales (4곳)',
      '',
      '⚡ **PromesBackfillTool — One-time 백필 도구**',
      '  ↳ 이미 import된 ProMES transaction에 imports[0] 1회 채움',
      '  ↳ delta = 누적 amount 그대로 (첫 entry로 간주)',
      '  ↳ 백필 완료 후 카드 자동으로 사라짐',
      '  ↳ ⚠ 주간 리포트를 사용하려면 1회 실행 필수',
      '',
      '✅ **사용 흐름**:',
      '  ① ProMES Import 1회 (이미 완료)',
      '  ② Settings → ⚡ ProMES Delta 백필 — 1회 클릭 (기존 데이터 호환)',
      '  ③ 매주 ProMES 다시 다운로드 → Import → 그 주의 delta 자동 추적',
      '  ④ Report → 주간 리포트 정상 표시 (신규 수주, 매출, 전주 대비)',
      '',
      '🏗 **월간 리포트 영향 없음**',
      '  ↳ order_amount는 마지막 누적값이라 월간 합계는 그대로 정확',
      '  ↳ 사업계획 대비 달성률, 전년 비교 등 모두 기존과 동일',
    ],
  },
  {
    version: 'v3.13.1',
    date: '2026-05-09',
    title: '🗑 영업현황 Import UI 제거 + Legacy 데이터 정리 도구',
    items: [
      '📌 **배경**: ProMES Import 단일 소스로 전환 — 영업현황_2026.xlsm 형식 import 기능 더 이상 불필요',
      '',
      '🚮 **Settings → 영업현황 Import 카드 제거**',
      '  ↳ ProMES Import만 노출 (UI 단순화)',
      '  ↳ Legacy 코드는 빌드에 포함되지 않도록 dead code 처리 (다음 cleanup에서 완전 제거)',
      '',
      '🆕 **Settings → 🗑 기존 영업현황 Import 데이터 정리 (One-time)**',
      '  ↳ 기존 source(excel_import_영업현황 / _S) 데이터 일괄 삭제',
      '  ↳ ProMES와 이중 집계 방지',
      '  ↳ 삭제할 데이터가 0건이면 카드 자동으로 숨김 (정리 완료 후 자동 사라짐)',
      '  ↳ ProMES source 데이터는 영향 없음',
      '',
      '✅ **사용 흐름**:',
      '  ① ProMES에서 원하는 연도 모두 다운로드 (수주.xlsx + 매출.xlsx)',
      '  ② Settings → 🆕 ProMES 영업통계 Import 실행',
      '  ③ Settings → 🗑 기존 영업현황 데이터 일괄 삭제 1회 실행',
      '  ④ 카드 자동으로 사라짐 → ProMES 단일 소스 운영',
    ],
  },
  {
    version: 'v3.13',
    date: '2026-05-09',
    title: '🆕 ProMES 영업통계 Import — 새 데이터 소스 연결',
    items: [
      '📌 **배경**: 영업현황_2026.xlsm이 더 이상 갱신되지 않음. ProMES 시스템에서 매출/수주를 별도 통계로 산출.',
      '  ↳ ProMES 영업통계 리포트 → "원본 Excel" 다운로드 (수주.xlsx + 매출.xlsx 분리)',
      '',
      '🆕 **Settings → ProMES 영업통계 Import (수주 + 매출)** 신규 카드',
      '  ↳ 수주.xlsx + 매출.xlsx 별도 선택 (한쪽만 import도 가능)',
      '  ↳ 시트명 "원본 데이터" 자동 감지',
      '  ↳ 헤더: 연도/분기/월/지역코드/지역명/거래처코드/거래처명/제품군코드/제품군명/건수/수량/금액(KRW)',
      '',
      '🔗 **Account 매칭 (3단계, 자동)**',
      '  ↳ ① external_code(거래처코드 C-00xxx) 매칭 — 가장 정확',
      '  ↳ ② company_name + alias 매칭',
      '  ↳ ③ 매칭 실패 시 신규 account 자동 생성 (external_code 자동 저장)',
      '  ↳ 기존 account에 코드가 없으면 import 시 자동 보강 (재import 정확도 향상)',
      '',
      '🧮 **dedupe 키 변경**',
      '  ↳ 기존: 수주번호 → 신규: `year-month-account_id-product_code`',
      '  ↳ 같은 키 다중 행 자동 합산 (금액/수량/건수)',
      '',
      '📅 **일자 정규화**',
      '  ↳ order_date / sale_date: 월 첫째 날 (`2026-01-01`) — 월간 리포트 호환',
      '  ↳ order_month / sale_month: `2026-01` 별도 저장',
      '  ↳ year, quarter 필드 별도 저장 (집계 빠르게)',
      '',
      '🚫 **금액 0원 자동 제외** (사용자 확인: 정상 수주/매출만 인식)',
      '  ↳ ProMES 통계가 이미 취소·샘플·수리 등 비정상 데이터 정제',
      '',
      '👤 **영업담당 컬럼 부재 영향 없음**',
      '  ↳ classifyForRepView가 plan/account 기반 attribution → transaction.sales_rep 미사용',
      '  ↳ 사업계획 매칭 거래처 → plan.sales_rep / 외 거래처 → 4 버킷',
      '',
      '📊 **리포트 영향**',
      '  ↳ ✅ 월간/연간 리포트: 기존과 동일',
      '  ↳ ✅ 담당자별 집계: 정상 작동',
      '  ↳ ⚠ 주간 리포트: 일자 월 단위 → "월목표 대비 누적실적" 표시는 정상',
      '',
      '🆔 **신규 데이터 필드**',
      '  ↳ accounts: external_code (거래처코드)',
      '  ↳ order_history / sales_history: external_code, product_code, region_code, order_month/sale_month, year, quarter, count',
      '  ↳ source: excel_import_promes_O / excel_import_promes_S',
      '',
      '🔄 **기존 영업현황 Import (Legacy 표시)**',
      '  ↳ 영업현황_2026.xlsm 형식 호환 유지 (참고용 보존)',
      '  ↳ source 분리: excel_import_영업현황 / excel_import_영업현황_S 그대로',
      '',
      '🌍 **mapRegion 보강**: ProMES 표기(M.E, L.America) 추가',
    ],
  },
  {
    version: 'v3.6.1',
    date: '2026-04-29',
    title: '💾 퍼지 매칭 Phase 2 — 실제 매칭 적용 도구',
    items: [
      '✅ **체크박스 선택**: 매칭 후보 테이블에 적용 체크박스 추가',
      '  ↳ 신뢰도 90% 이상은 자동 체크 (안전한 default)',
      '  ↳ 의심스러운 매칭(70~89%)은 사용자가 직접 검토',
      '',
      '🎛 **빠른 선택 버튼**: [전체 선택] [신뢰도 90%+ 만] [전체 해제]',
      '',
      '💾 **매칭 적용 버튼**: 선택 항목 일괄 처리',
      '  ↳ 사업계획 plan들의 account_id를 영업현황 account ID로 연결',
      '  ↳ 고객 이름은 변경 없음 (사업계획 customer_name 유지)',
      '  ↳ Firestore batch save (빠름)',
      '  ↳ Report 통계가 즉시 정확해짐 (사업계획 달성률, 전년대비 등)',
      '',
      '🛡 **안전성**:',
      '  ↳ confirm 알림으로 사용자 의도 재확인',
      '  ↳ 데이터 손실 없음 (account 통합/삭제 X, ID 연결만)',
      '  ↳ 적용 후 자동 재분석 (다음 라운드 검토 가능)',
    ],
  },
  {
    version: 'v3.6',
    date: '2026-04-27',
    title: '🔍 고객명 퍼지 매칭 분석기 (Dry-run) — 사업계획 ↔ 영업현황 통합 점검',
    items: [
      '🎯 **문제 인식**: 사업계획 고객명과 영업현황 고객명이 100% 일치하지 않아 통계 왜곡',
      '  ↳ 예: "Fannin Healthcare" ↔ "Fannin Healthcare Inc." → 별도 account로 분리',
      '  ↳ 결과: 사업계획 달성률·재구매·전년대비 등 통계 부정확',
      '',
      '🔧 **신규 라이브러리**: src/lib/fuzzyMatch.js',
      '  ↳ 정규화: 대소문자/공백/회사 접미사(Inc/Ltd/Co/주식회사 등) 제거',
      '  ↳ Levenshtein distance (편집 거리) 기반 문자열 유사도',
      '  ↳ Jaccard similarity (토큰 교집합) 기반 단어 매칭',
      '  ↳ 종합 점수 (0~1) + 신뢰도 등급 (완벽/매우높음/높음/보통/낮음)',
      '',
      '📊 **Settings 신규 섹션**: 🔍 고객명 퍼지 매칭 분석',
      '  ↳ 신뢰도 임계값 5단계 선택 (50%~85%)',
      '  ↳ Dry-run: 분석만 진행, 데이터 변경 없음',
      '  ↳ 결과 표시:',
      '    · 매칭 후보 리스트 (영업현황 → 사업계획, 신뢰도, 수주/매출 금액)',
      '    · 매칭 실패 리스트 (최근접 후보 + 점수)',
      '    · 매칭 적용 시 사업계획 실적 보강 효과 (+얼마)',
      '    · 통계 변화 미리보기',
      '',
      '📌 **다음 단계 (Phase 2)**: 결과 검증 후 매칭 적용 도구 (선택 항목 일괄 통합)',
    ],
  },
  {
    version: 'v3.5.1',
    date: '2026-04-25',
    title: '🐛 수주/매출 Import — Firestore 잔여 데이터 정리 + 25배 빠른 일괄 삭제',
    items: [
      '🐛 **버그 수정**: 재Import 후에도 기존 매출 데이터가 그대로 남던 문제',
      '  ↳ 원인: 삭제 로직이 React state 기반이라 Firestore의 어제 잔여 데이터를 인식 못 함',
      '  ↳ 수정: Firestore에서 source 기준 직접 query 후 batch 삭제 (state 무관)',
      '',
      '⚡ **삭제 속도 25배 향상**',
      '  ↳ 이전: deleteDoc 하나씩 순차 (10,000건 = 약 18분 😱)',
      '  ↳ 이후: writeBatch 500건 일괄 (10,000건 = 약 40초 ⚡)',
      '',
      '💬 **명확한 진행 토스트 메시지**',
      '  ↳ 이전: "10,000건 import 완료"',
      '  ↳ 이후: "수주 import 완료: 기존 12,000건 삭제 → 신규 4,500건"',
      '',
      '📢 **사용자 조치**: 영업현황 재Import → 한 번에 깨끗하게 정리됨',
    ],
  },
  {
    version: 'v3.5',
    date: '2026-04-25',
    title: '✎ Activity Log 전면 개편 — 편집·수정이력·완료처리·활동발생일',
    items: [
      '📅 **활동 발생일 사용자 입력** (이전: 자동 오늘 날짜 고정)',
      '  ↳ 폼에 "활동 발생일" 필드 추가, 기본값 오늘',
      '  ↳ 과거 활동도 실제 발생일로 기록 가능 → 주간/월간 리포트 정확성',
      '',
      '🔀 **폼 필드 재배치**',
      '  ↳ 상단: [활동 발생일] [이슈 유형] [중요도]',
      '  ↳ 하단: [다음 액션] [다음 액션 기한] ← 짝으로 묶음 (기한 의미 명확화)',
      '',
      '✎ **편집 기능 추가** (기존에는 삭제 후 재입력만 가능)',
      '  ↳ 각 로그 카드에 "✎ 편집" 버튼 → 인라인 편집 모드',
      '  ↳ 권한: 본인 작성 로그만 편집 가능',
      '  ↳ 👑 관리자(admin)는 모든 로그 편집 가능',
      '  ↳ 편집 불가 로그는 "(본인 로그만 편집 가능)" 표시',
      '',
      '📜 **수정 이력 자동 기록**',
      '  ↳ 모든 수정 시 edit_history 배열에 저장',
      '  ↳ 언제 / 누가 / 어느 필드 변경했는지 기록',
      '  ↳ 카드 우측 "✎ N회 수정" 배지 클릭 → 상세 이력 펼침',
      '',
      '🏁 **완료 처리 시 처리 결과 필수 기록**',
      '  ↳ "완료" 버튼 클릭 → 팝업 자동 오픈',
      '  ↳ 처리 결과 설명 (필수, textarea)',
      '  ↳ 해결 방법 태그 (8종): 🤝 합의 / ✅ 요청수용 / 💰 환불 / 🔄 교환 / ❌ 거절 / ⏸ 보류 / 📤 타부서이관 / 📌 기타',
      '  ↳ 실제 해결일 (예정일과 달라질 수 있음)',
      '  ↳ 완료된 이슈 카드에 초록색 "🏁 처리 결과" 블록 표시',
      '',
      '🔐 **삭제 권한**: 본인 또는 관리자만 가능',
    ],
  },
  {
    version: 'v3.4',
    date: '2026-04-24',
    title: '🏗️ localStorage 의존 제거 + Exec Summary Firestore 통합 + Import 개선',
    items: [
      '🚀 **근본 해결**: localStorage quota 초과로 인한 흰 화면 재발 방지',
      '  ↳ 대용량 전체 데이터 백업(STORAGE_KEY) 완전 제거',
      '  ↳ Firebase Firestore가 원본 소스 — 모든 데이터 실시간 구독',
      '  ↳ 오프라인 fallback은 개별 작은 키(auth, teamMembers 등)만 유지',
      '',
      '☁️ **Exec Summary + 다음 달 계획 Firestore 이전**',
      '  ↳ 이전: localStorage (해당 브라우저에서만, 손실 위험)',
      '  ↳ 이후: app_settings 컬렉션 (여러 PC/브라우저 공유 + 영구 보관)',
      '  ↳ 일회성 마이그레이션: 기존 localStorage 값 자동 이관',
      '  ↳ 500ms 디바운싱으로 타이핑 중 Firestore 쓰기 최적화',
      '',
      '📅 **영업현황 Import 개선 재적용 (v3.3.1 롤백 분 복구)**',
      '  ↳ "🌐 전체 연도" 옵션 추가 (기본값) — 전년도 실적까지 포함',
      '  ↳ 단일 연도 선택 시 "⚠ 전년대비 비교 불가" 경고',
      '  ↳ excelDateToStr 강화 — 다양한 문자열 날짜 정규화',
      '    · ISO · YYYY/M/D · M/D/YYYY · D.M.YYYY · Date fallback',
      '',
      '📢 **사용자 조치**: Settings → "영업현황 엑셀 선택" → "전체 연도" 선택 후 Import → 주간/월간 리포트에 전년동월·전년YTD 표시 확인',
    ],
  },
  {
    version: 'v3.3',
    date: '2026-04-24',
    title: '🏆 월간 리포트 Phase C — 5페이지 스토리텔링 + 팀별 TASK + Pipeline 하이브리드',
    items: [
      '📄 #13 5페이지 스토리텔링 구조 (Chapter Header + 인쇄 페이지 구분)',
      '  ↳ Page 1 (Executive Summary): KPI · 전년동기 · 자동 요약 · 핵심 메시지',
      '  ↳ Page 2 (Key Metrics): 월별 수주/매출 · 팀별/담당자별 실적',
      '  ↳ Page 3 (Strategic Analysis): 팀별 활동+GAP · 고객별 · 4-3 GAP 심층',
      '  ↳ Page 4 (Next Month Actions): 다음 달 계획 · 차월 파이프라인 · 팀별 TASK',
      '  ↳ Page 5 (Pipeline CRM & Deep Analysis): 신규 딜 + 심층 Gap 원인',
      '  ↳ 화면에 페이지 배너 표시 + 인쇄 시 자동 페이지 구분',
      '',
      '✅ #14 팀별 월간 TASK 기능 (신규)',
      '  ↳ Firestore `team_tasks` collection CRUD',
      '  ↳ 고정 5유형: 🎯 수주만회 / 📋 계약갱신 / 🚀 신규딜 / 🔀 Cross-Selling / 📌 기타',
      '  ↳ 해외영업/BPU/국내영업 3팀 각각 카드 형태',
      '  ↳ 우선순위 P1/P2/P3 + 상태(Open/In Progress/Done) + 담당자/마감일',
      '  ↳ 상태 배지 클릭으로 Open → In Progress → Done 순환',
      '  ↳ 편집(✎) / 삭제(×) / 추가(+ TASK) 버튼',
      '',
      '🔗 #15 Pipeline CRM 하이브리드 통합 (신규)',
      '  ↳ Pipeline CRM의 `customers` 컬렉션 read-only 구독',
      '  ↳ Proposal/Evaluation/Closing 단계 딜만 필터링, 금액 높은 순 TOP 10',
      '  ↳ 예상금액 × 확률 = 가중금액 자동 계산',
      '  ↳ "Pipeline CRM 열기 ↗" 버튼으로 원본 앱 연결',
      '',
      '📋 Phase A/B/C 통합 완료 — 경영진 월간 보고 전면 재구성',
    ],
  },
  {
    version: 'v3.2',
    date: '2026-04-23',
    title: '🎯 월간 리포트 Phase B — 경영진 스토리텔링 강화',
    items: [
      '🤖 #1 자동 Executive Summary 박스 추가',
      '  ↳ KPI/GAP/파이프라인 기반 자동 요약 4줄 + 자동 종합 판단 (🟢/🟡/🔴)',
      '  ↳ 수동 섹션(0번) 위에 배치, 수동으로 편집 가능',
      '📊 #7 GAP 심층분석 요약 박스 추가',
      '  ↳ 미달/초과 고객 수·금액, 순 Gap, FCST catch-up 잠재 한눈에',
      '  ↳ 주요 원인 TOP3 태그 표시',
      '👥 #4 팀별 월간 활동에 GAP 원인 통합',
      '  ↳ 각 팀 카드에 "🔴 미달 고객수 · Gap 금액 · 원인 TOP2" 표시',
      '  ↳ 해외/BPU/국내 사업부별 책임 명확화',
      '🎯 #8 "재구매 임박" → "차월 수주 파이프라인" 재구성',
      '  ↳ 수주 가능액 + 신뢰도 (FCST 80% / 사업계획 60% / 트렌드 40%)',
      '  ↳ 가중금액 자동 계산, P1/P2/P3 우선순위 자동 분류 (가중금액 누적 50%/80%)',
      '  ↳ 전체 예상·가중 금액 한눈에, 고객명 클릭 → 상세카드',
      '📅 #2 전년실적 반영 (기존 v3.0 완료분 확인)',
      '  ↳ KPI 4카드에 전년비 % · 전년동기 비교표(MTD+YTD) · 월별 트렌드 전년 행 모두 반영됨',
      '🗑️ 레거시 Section 1~5 전면 제거 (KPI/차트/분류별/고객별/Cross-Selling/FCST)',
      '  ↳ 이미 상단 ■1~4-3에 통합된 중복 섹션',
      '',
      '📋 다음 단계 (Phase C)',
      '  · #14 팀별 TASK 기능 (team_tasks Firestore collection — 인프라 준비 완료)',
      '  · #15 Pipeline CRM 신규 딜 하이라이트 (customers 구독 — 인프라 준비 완료)',
      '  · #13 5페이지 스토리텔링 구조 재구성',
    ],
  },
  {
    version: 'v3.1',
    date: '2026-04-23',
    title: '📊 월간/주간 리포트 Phase A 간소화 — 중복 제거 + 경영진 가독성 개선',
    items: [
      '🗑️ #3 월간 "2-2 팀별 월간 매출" 섹션 제거 — KPI 및 1-2에서 이미 확인 가능',
      '🗑️ #5 월간 "Top 10 거래처" 제거 — GAP 심층 분석과 중복',
      '🔀 #6 "고객별 당월 수주" 정렬 변경 — 달성률 낮은 순 → **높은 순** (성과 우선 표시)',
      '🗑️ #9 주간/월간 "상세 분석" 섹션 제거',
      '  ↳ 주간: 금주 수주 현황/활동 요약/당월 분류별 실적/Open 이슈 등 전체 블록 제거 (팀별 통합 블록으로 정보 충분)',
      '  ↳ 월간: "상세 분석" 타이틀 제거 (월간 리포트 전체가 상세 분석이므로 중복 표현)',
      '🗑️ #10 고객유형별(typeRows/typeMonthRows) 제거 — 사업구분별과 중복, 사용처 없음',
      '🗑️ #12 AM별 활동 품질 지표에서 "액션 실행률" 컬럼 제거 (화면 + Excel export)',
      '',
      '📋 다음 단계 (Phase B, C)',
      '  · Phase B: Executive Summary 자동생성, 전년대비, GAP 요약+상세, 재구매 재구성',
      '  · Phase C: 5페이지 스토리텔링 재구조화 + 팀별 TASK + Pipeline CRM 하이브리드',
    ],
  },
  {
    version: 'v3.0.4',
    date: '2026-04-20',
    title: '🚨 근본 원인 수정 — customerPlans 필터에 team_sales 섞임 버그',
    items: [
      '🐛 전 시스템 동일 버그: p.type !== "product" 필터 → team_sales까지 포함됨',
      '  ↳ 결과: 수주 목표 계산에 매출 목표(team_sales)가 섞여 "수주 = 매출" 동일 출력',
      '  ↳ 수정: p.type === "customer" || !p.type 로 명시적 필터',
      '📁 14개 파일 일괄 수정 — Report/Dashboard/OrderReport/Progress/Settings/GapAnalysis/AccountList',
      '💡 이 버그로 인해 이전 v3.0~3.0.3 Fallback 로직이 반대로 작동: team_sales 있어도 수주 목표로 잘못 사용',
    ],
  },
  {
    version: 'v3.0.3',
    date: '2026-04-20',
    title: '사업계획 Import 버그 수정 — 고객별 시트 없어도 Import 가능',
    items: [
      '🐛 버그 수정: 고객별 시트 없는 사업계획 파일 Import 실패 문제',
      '  ↳ 이전: `wb.SheetNames[0]`(Sheet1, 메모) 선택 → 헤더 못찾아 에러',
      '  ↳ 이후: 고객별 시트 없어도 매출 목표/품목별 있으면 Import 진행',
      '🔐 Type별 plan 교체 로직 (중요!)',
      '  ↳ 이전: 매출 목표만 있는 파일 Import 시 기존 수주목표 모두 삭제됨',
      '  ↳ 이후: 해당 type(team_sales / customer / product)만 교체, 다른 type 유지',
      '📘 Settings UI 재정리 — 두 파일 유형 명확 안내',
      '  ↳ ① 수주목표 파일 (고객별 시트)',
      '  ↳ ② 사업계획 파일 (수주매출S 시트)',
      '  ↳ 각각 순서대로 업로드 가능',
    ],
  },
  {
    version: 'v3.0.2',
    date: '2026-04-20',
    title: '매출 목표 시트 선택 + 중복 행 문제 완전 해결',
    items: [
      '✅ 매출 목표 시트 우선순위 변경 — "26년도 월별수주매출S_*" 시트 최우선 선택',
      '  ↳ 이전: "월별매출" 시트 우선 (구버전/보수적 목표, 해외 164.5억)',
      '  ↳ 이후: "월별수주매출S" 시트 우선 (최신 시뮬레이션, 해외 215.6억)',
      '✅ "국내" 행 중복 합산 버그 수정 — Excel 레이아웃의 중복 행 자동 스킵',
      '  ↳ 국내(첫 행, 합계) + 국내(대리점) + 국내(직판) → 첫 행만 사용',
      '🎯 검증 결과 — 사용자 기준 파일과 100% 일치:',
      '  · 해외 215.62억 / BPU 67.87억 / 국내 37.97억 / Total 321.45억',
    ],
  },
  {
    version: 'v3.0.1',
    date: '2026-04-20',
    title: '매출 목표 Import 단위 오류 수정',
    items: [
      '🐛 매출 목표 Import 단위 변환 오류 수정 (×1000 곱셈 제거)',
      '  ↳ 사업계획 Excel은 헤더에 "[단위: 천원]"이지만 실제 셀 값은 원 단위',
      '  ↳ 수주 목표와 동일 방식으로 값 그대로 저장',
      '📢 Import 성공 메시지에 연간 매출목표 금액 명시 (검증 용이)',
      '⚠ 기존 Import된 team_sales plan은 Settings에서 재 Import 필요 (값이 1000배 큼)',
    ],
  },
  {
    version: 'v3.0',
    date: '2026-04-20',
    title: '매출 목표 대비 실적 반드시 표시 (Fallback 로직)',
    items: [
      '💰 매출 목표 표시 보장 — team_sales plan 미Import 상태에서도 매출 달성률 표시',
      '  ↳ 1순위: 사업계획 월별매출 시트 → team_sales plan (전용 매출목표)',
      '  ↳ 2순위 Fallback: customerPlans 수주목표를 팀별 집계하여 자동 사용',
      '  ↳ 주간·월간 리포트 모두 동일 로직 적용',
      '🏷 UI 투명성 — Fallback 사용 중일 때 "수주목표 기반 대체" 라벨 명시',
      '  ↳ 사용자가 전용 매출목표 Import 필요성 인지 가능',
    ],
  },
  {
    version: 'v2.9',
    date: '2026-04-20',
    title: '담당자 분류 일관성 완성 + 매출목표 Import 강화',
    items: [
      '🚨 담당자 분류 최종 통합 — "분류별 실적 상세 > 담당자별"의 영업현황 rep(Lijian/Milena/이다은 등) 완전 제거',
      '  ↳ monthlyData.repMonthRows 및 planSummary.byRep 모두 classifyForRepView() 강제 사용',
      '  ↳ 사업계획 담당자 + teamMembers + 4개 버킷(국내기타/해외기타/국내신규/해외신규)만 노출',
      '💰 매출 목표 Import 유연성 강화 — 여러 후보 시트 자동 탐색 ("월별매출", "월별수주매출S" 등)',
      '  ↳ 데이터가 있는 시트 우선 선택, 비어있으면 명확한 경고 메시지',
      '  ↳ 담당자배정 버전(_v10_담당자배정.xlsx)은 매출목표 비어있음 → _251229 버전 사용 안내',
      '📋 재발 방지: 담당자 분류 규칙 문서·코드 주석 강화',
      '  ↳ customerClassification.js 상단 주석에 ⚠️ 절대 규칙 명기',
      '  ↳ WORKFLOW.md / MEMORY.md에도 금지 패턴 + 점검 명령어 추가',
    ],
  },
  {
    version: 'v2.8',
    date: '2026-04-20',
    title: '주간 리포트 팀별 블록 전면 재구성 — 금주활동·주요이슈·Open·차주·리스크',
    items: [
      '🏢 수주·매출 현황에서 "기타" 행 제거 — 해외/BPU/국내 3사업부만 표시 (region fallback 자동)',
      '📊 주간 리포트 간소화 — YTD 사업계획 진도·차트·고객유형별 제거, 당월(MTD) 기준으로 통일',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🎯 Activity Log 중요도(priority) 필드 추가 — 🟢일반 / 🟡주요 / 🔴긴급',
      '  ↳ 입력·수정 UI 모두 지원, 로그 카드에 배지 표시',
      '  ↳ 주요이슈 자동 집계 기준: priority ≥ 2 (🟡주요+🔴긴급)',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '👥 주간 리포트 팀별 통합 블록 신규 (해외/BPU/국내 각각)',
      '  📊 금주 활동 — 컨택/수주활동/가격협의/샘플/크로스셀링 건수',
      '  🔴 주요 이슈 — 금주 발생 + priority≥주요 자동 집계 (수동 입력 불필요)',
      '  ⏳ Open 이슈 — 고객 단위 그룹핑 + P1/P2/P3 자동 우선순위 + 토글 드릴다운',
      '     (P1: priority≥긴급 or 14일+A·B등급 or 품질클레임 or 5건+ / P2: 7일+ or 2건+ / P3: 그 외)',
      '  📅 차주 계획 — 다음주 due + 금주 미완료 이월 통합',
      '  ⚠ 리스크 — 재구매 임박 + 계약만료 D-60 + 14일+ 미해결',
      'Excel Export 동일 구조로 재구성',
    ],
  },
  {
    version: 'v2.7',
    date: '2026-04-18',
    title: '월간 리포트 완성 — 담당자 재정립 + 신규/기타 분류 + GAP 심층 분석',
    items: [
      '👥 담당자별 실적 테이블 전면 재구성 (주간 + 월간 리포트 모두)',
      '  ↳ 사업계획상 담당자 + teamMembers만 표시 (그 외 모두 제외)',
      '  ↳ 국내기타·해외기타·국내신규·해외신규 4개 버킷 자동 집계',
      '  ↳ 전년도 수주 없는 고객 = "신규"로 자동 분류',
      '🔽 신규·기타 고객 토글 드릴다운 — ▸ 클릭 시 고객 리스트 펼침 (클릭 시 상세카드 이동)',
      '📊 대시보드 담당자별 목표 vs 실적 — 동일 분류 체계 적용 (system-wide 일관성)',
      '📈 OrderReport 담당자 필터 — 중앙화된 salesReps 규칙 적용',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🎯 GAP 분석 탭 개선 (고객카드):',
      '  ↳ 초과/미달 자동 판별하여 배지 표시',
      '  ↳ "대책" 필드 신규 추가 (부족분 만회 계획) / 초과 시 "지속 발전 요소"',
      '  ↳ 상세 설명란의 플레이스홀더 상황별 자동 변경',
      '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━',
      '🔍 월간 리포트 섹션 4-3 — 고객별 GAP 심층 분석 신규 (#7·#8·#9)',
      '  ↳ 미달 고객 TOP 10 (YTD 90% 미만) + 초과 고객 TOP 5 (YTD 110% 초과)',
      '  ↳ 각 고객별 통합 뷰: GAP분석(원인/상세/대책/경쟁메모/기회)',
      '  ↳ 연관 정보 자동 집계: 전략등급, 컨텍스트, 최근 3개월 이슈, 계약만료 임박, 전년비, Cross-selling',
      '  ↳ 📈 FCST Catch-up 자동 코멘트 — 향후 FCST가 Gap 만회하면 "N월까지 회복 예상" 자동 생성',
      '  ↳ 부분 만회 시 "FCST 반영 연간 달성률 XX% 예상"',
    ],
  },
  {
    version: 'v2.6',
    date: '2026-04-18',
    title: '월간 리포트 마무리 Phase 1 — KPI 카드 + 전년동기 + YTD + 고객별 미달',
    items: [
      '📊 월간 KPI 4종 카드 (수주 MTD·YTD + 매출 MTD·YTD, 달성률 + 전년비)',
      '📈 전년동기 대비 비교 표 — 수주·매출 각각 MTD/YTD × 증감액/증감률',
      '📋 YTD 누적 달성률 신규 표시 (기존에는 YTD 실적만 있어 달성률 확인 어려움)',
      '👥 고객별 당월 실적 표 — 목표 설정된 모든 고객 포함 (실적 0 포함), 달성률 낮은 순 정렬 (미달 우선 노출)',
      '  ↳ 고객명 클릭 시 상세 카드 열림, YTD Gap / 당월 Gap 자동 표시',
      '🔢 당월 분류별 실적 정렬 변경 — 연간 목표 순 → 당월 달성률 높은 순',
      '🧰 공통 유틸리티 중앙화 — customerClassification 확장(국내·해외 신규 세분화), salesReps 신설',
    ],
  },
  {
    version: 'v2.5',
    date: '2026-04-17',
    title: '매출 데이터 정확도 개선 — S시트/사업계획 매출 목표 수정',
    items: [
      '🔧 영업현황 S시트 컬럼 매핑 수정 — 실제 컬럼명 기준(고객사/매출금액/B/L Date)으로 교체',
      '  ↳ 기존에는 O시트와 동일 구조로 가정하여 매출 데이터 import 대부분 실패 상태였음',
      '  ↳ B/L Date 있고 매출금액 > 0 인 행만 "매출 확정"으로 처리, 매출대기는 별도 필드에 보관',
      '📊 사업계획 매출 목표 Import 추가 — 월별매출 시트의 "사업부별 매출" 영역 자동 파싱',
      '  ↳ 해외/BPU/국내(국내+국내(직판) 3행 자동 합산) 사업부별 월별 매출 목표 저장',
      '  ↳ type: "team_sales" plan 신설 (연/월/팀/목표)',
      '📈 주간·월간 리포트 매출 현황 수정 — 3개 사업부(해외/BPU/국내(직판포함)) 기준으로 표시',
      '  ↳ 달성률은 사업계획 팀별 매출 목표 대비 실적 (BEP·생산 CAPA 모니터링용)',
    ],
  },
  {
    version: 'v2.4',
    date: '2026-04-17',
    title: '주간 리포트 종합 개선 + 매출 데이터 Import',
    items: [
      '📊 YTD → MTD 전환 — 주간 KPI를 월단위 중심으로 재구성',
      '📅 분기별 진행 현황 표 추가 — Q1~Q4 목표/실적/달성률, 완료/진행중/예정 상태 표시',
      '👥 담당자 활동 전원 표시 — 배정 고객수 컬럼 + 컨택율 + 활동 0 담당자도 포함',
      '🔄 미완료 이슈 자동 이월 — 금주 Closed 안된 이슈가 차주 액션에 "이월" 배지로 자동 표시',
      '🖨 PDF 페이지 분할 개선 — #app 높이 제한 해제, 섹션별 page-break, 행 단위 분할',
      '🔵🟢🟡 재구매 알람 3유형 구분 — FCST(파랑) / 사업계획(초록) / 트렌드(노랑) 독립 표시',
      '  ↳ 사업계획 신규 로직 — targets[월]에 금액 있고 80% 미달성 시 D-30/D-14 단계 알람',
      '💰 매출 데이터 Import — S 시트(B/L date 기준) 동시 업로드, sales_history 컬렉션',
      '📈 주간/월간 리포트 매출 섹션 — 수주와 나란히 "매출 현황" 테이블 병행 표시',
      '  ↳ 월별 매출 추이표(12개월) + 팀별 월간 매출 테이블',
    ],
  },
  {
    version: 'v2.3',
    date: '2026-04-17',
    title: '월간 리포트 스펙 기반 재구성 (섹션 A~E)',
    items: [
      '🗓️ 월 네비게이터 — ◀이전 월 / 다음 월▶ 탐색, 기본값은 직전 완료 월',
      '📝 섹션 A — Executive Summary (핵심 메시지 3개 + 종합 판단 + 다음달 집중, 월별 자동 저장)',
      '📊 섹션 B-1 — 월별 실적 추이표 (전년실적/목표/실적/전년대비/목표대비) 12개월 × 합계',
      '🏢 섹션 B-2 — 팀별 월간 실적 (해외/BPU/국내 × 목표/실적/달성률/전년대비)',
      '👥 섹션 C — 팀별 월간 활동 분석 (Activity/신규계약/Cross-selling/미해결/컨택 + 주요이슈 TOP5)',
      '🥇 섹션 D — 주요 거래처별 실적 상위 10사 (당월/전월/증감률)',
      '📅 섹션 E — 다음 달 사업 계획 (팀별 수동 입력 + 재구매 D-30 + 계약만료 D-60 자동 나열)',
      '📥 Excel Export 2시트 — 매출-수주 Raw(값) + 월간종합_(MM월) 스펙 레이아웃',
    ],
  },
  {
    version: 'v2.2',
    date: '2026-04-16',
    title: '종합 리포트 — 주간 수주 현황 (섹션 A)',
    items: [
      '📊 주간 수주 현황 테이블 — 팀별(해외/BPU/국내) 전주 누적 · 금주 신규 · 당월 누적 · 당월 목표 · 달성률 자동 집계',
      '🗓️ 주차 네비게이터 — ◀이전 주 / 다음 주▶ 탐색, N월 N주차 라벨 표시',
      '🎯 달성률 색상 코딩 — ≥100% 파랑 / 80~99% 검정 / <80% 빨강',
      '📋 주간 이슈사항 자동 집계 — Activity Log를 영업이슈/고객지원/품질이슈/기타로 자동 분류, 팀별 표시',
      '📅 다음 주 예정 액션 — 기한 도래 액션 + 재구매 임박 고객(D-14) 자동 표시',
      '📥 Excel Export — 스펙 기반 주간종합 시트 (섹션 A/B/C + 부록)',
    ],
  },
  {
    version: 'v2.1',
    date: '2026-04-16',
    title: '수주목표관리 개선 + 계약상태 모니터링',
    items: [
      '💱 통화 KRW 통일 — FCST/수주실적/목표 모두 원화(억/만) 표시로 통합',
      '📊 GAP 컬럼 추가 — 월별/분기/연간 (목표 - 확정 - FCST) 갭 자동 계산',
      '📋 계약 체결 현황 — 🟢계약체결 / 🟡FCST협의 / 🔴미체결 상태 대시보드 모니터링',
      '⚠️ 목표 미달 경고 — 확정+FCST가 목표에 미달하는 고객 대시보드 알람',
      '👤 담당자 필터 정리 — 수주목표관리 필터에서 불필요한 담당자 제거',
      '🐛 계약수량 저장 오류 수정 — 기존 계약 편집 시 수량이 새로고침 후 사라지는 버그 해결',
    ],
  },
  {
    version: 'v2.0',
    date: '2026-04-13',
    title: 'Customer Insight 통합 + 전략등급',
    items: [
      '🎯 전략 등급(A/B/C/D) 도입 — 고객 목록/대시보드에서 등급별 필터 및 분포 확인',
      '🔍 Customer Insight 탭 통합 — 기존 Score + 비즈니스 건강도 + 공급자 지위 + 구매결정 구조를 하나의 탭으로 통합',
      '⚡ 자동 감지 — 기본정보/가격계약 탭에 입력된 데이터를 자동으로 Insight 진척률에 반영',
      '📝 현재 컨텍스트 메모 — 고객 현황 한 줄 요약 (기본정보 탭 + 모달 헤더에 표시)',
      '⚠️ Watch 알람 — D등급 고객 + 진척률 30% 미만 고객 대시보드 알람',
      '📋 업데이트 알림 — 이 팝업! 새 버전 배포 시 변경 내역 자동 표시',
    ],
  },
  {
    version: 'v1.9',
    date: '2026-04-13',
    title: 'FCST 월별 전환 + 수주목표관리',
    items: [
      '📈 수주목표관리 리포트 뷰 신규 추가 (목표/확정수주/FCST 월별 테이블)',
      '📊 FCST 월별 입력 전환 (분기별→월별, 기존 데이터 호환)',
      '✏️ 리포트 내 FCST 인라인 편집 (셀 클릭→직접 입력)',
      '💰 가격·계약: 계약수량 + 계약금액 자동계산 추가',
    ],
  },
];

export const CURRENT_VERSION = CHANGELOG[0].version;
export const VERSION_STORAGE_KEY = 'bioprotech_account_crm_version';
